import type { HeroDefinition } from '../types/hero';

export const HERO_REGISTRY: Record<string, HeroDefinition> = {
  layla: {
    id: 'layla',
    name: 'Layla',
    title: 'Energy Gunner',
    heroClass: 'marksman',
    primaryRole: 'gold_lane',
    avatar: '🔫',
    color: '#06b6d4', // Cyan
    accentColor: '#38bdf8',
    baseStats: {
      maxHp: 2500,
      hpRegen: 28,
      maxMana: 450,
      manaRegen: 15,
      physicalAttack: 130,
      magicPower: 0,
      physicalDefense: 15,
      magicDefense: 10,
      attackSpeed: 1.05,
      movementSpeed: 8.5,
      attackRange: 8.5, // High range
      critChance: 0.1,
      critDamage: 2.0,
      cooldownReduction: 0,
      physicalLifesteal: 0,
      magicLifesteal: 0,
      physicalPenetration: 0,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 150,
      manaPerLevel: 30,
      physAtkPerLevel: 10,
      armorPerLevel: 3.2,
    },
    passive: {
      name: 'Malefic Gun',
      description: 'Basic attack and skill range increases with hero level (up to +30% at level 15).',
      icon: '🎯',
    },
    skills: [
      {
        id: 'layla_s1',
        name: 'Malefic Bomb',
        description: 'Fires an energy bomb in a line, dealing physical damage and granting +60% movement speed on hit.',
        icon: '💥',
        maxLevel: 4,
        cooldownByLevel: [6, 5.5, 5, 4.5],
        manaCostByLevel: [40, 45, 50, 55],
        castRange: 11,
        radius: 1.2,
        skillType: 'skillshot',
        damageType: 'physical',
        baseDamageByLevel: [200, 260, 320, 380],
        scalingRatio: 1.4,
      },
      {
        id: 'layla_s2',
        name: 'Void Projectile',
        description: 'Fires an energy orb that detonates, dealing physical damage, slowing targets by 40%, and marking them for extra magic damage.',
        icon: '🌐',
        maxLevel: 4,
        cooldownByLevel: [8, 7.5, 7, 6.5],
        manaCostByLevel: [65, 70, 75, 80],
        castRange: 9.5,
        radius: 3.0,
        skillType: 'aoe',
        damageType: 'physical',
        baseDamageByLevel: [170, 220, 270, 320],
        scalingRatio: 0.8,
        crowdControl: {
          type: 'slow',
          duration: 1.5,
          intensity: 0.4,
        },
      },
      {
        id: 'layla_s3',
        name: 'Destruction Rush',
        description: 'Charges and fires an enormous high-energy beam through the battlefield, dealing colossal physical damage to all enemies in its path.',
        icon: '⚡',
        maxLevel: 3,
        cooldownByLevel: [35, 30, 25],
        manaCostByLevel: [130, 150, 170],
        castRange: 18, // Super long range
        radius: 2.2,
        skillType: 'skillshot',
        damageType: 'physical',
        baseDamageByLevel: [500, 700, 900],
        scalingRatio: 1.8,
      },
    ],
    recommendedBuild: ['swift_boots', 'windtalker', 'berserkers_fury', 'demon_hunter_sword', 'blade_of_despair', 'immortality'],
    spellId: 'flicker',
  },

  miya: {
    id: 'miya',
    name: 'Miya',
    title: 'Moonlight Archer',
    heroClass: 'marksman',
    primaryRole: 'gold_lane',
    avatar: '🏹',
    color: '#818cf8', // Indigo
    accentColor: '#a5b4fc',
    baseStats: {
      maxHp: 2520,
      hpRegen: 30,
      maxMana: 440,
      manaRegen: 15,
      physicalAttack: 125,
      magicPower: 0,
      physicalDefense: 17,
      magicDefense: 10,
      attackSpeed: 1.1,
      movementSpeed: 8.6,
      attackRange: 7.5,
      critChance: 0.1,
      critDamage: 2.0,
      cooldownReduction: 0,
      physicalLifesteal: 0.05,
      magicLifesteal: 0,
      physicalPenetration: 0,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 145,
      manaPerLevel: 32,
      physAtkPerLevel: 9.5,
      armorPerLevel: 3.1,
    },
    passive: {
      name: 'Moon Blessing',
      description: 'Each basic attack grants +5% attack speed for 4s, stacking up to 5 times. At full stacks, summons Moonlight Shadow to split attack.',
      icon: '🌙',
    },
    skills: [
      {
        id: 'miya_s1',
        name: 'Moon Arrow',
        description: 'Miya empowers her bow for 4s, firing two split arrows alongside her primary basic attack to strike multiple nearby enemies.',
        icon: '✨',
        maxLevel: 4,
        cooldownByLevel: [10, 9, 8, 7],
        manaCostByLevel: [60, 70, 80, 90],
        castRange: 0,
        radius: 0,
        skillType: 'self',
        damageType: 'physical',
        baseDamageByLevel: [50, 70, 90, 110],
        scalingRatio: 0.5,
      },
      {
        id: 'miya_s2',
        name: 'Arrow of Eclipse',
        description: 'Launches a rain of moon arrows at the targeted area, dealing damage and immobilizing enemies in the center ring for 1.2s.',
        icon: '🌧️',
        maxLevel: 4,
        cooldownByLevel: [10, 9.5, 9, 8.5],
        manaCostByLevel: [80, 90, 100, 110],
        castRange: 8.5,
        radius: 3.2,
        skillType: 'aoe',
        damageType: 'physical',
        baseDamageByLevel: [160, 210, 260, 310],
        scalingRatio: 0.9,
        crowdControl: {
          type: 'stun',
          duration: 1.2,
        },
      },
      {
        id: 'miya_s3',
        name: 'Hidden Moonlight',
        description: 'Immediately removes all crowd control effects, enters invisible stealth for 2.0s, and gains +45% bonus movement speed.',
        icon: '🌑',
        maxLevel: 3,
        cooldownByLevel: [36, 32, 28],
        manaCostByLevel: [120, 135, 150],
        castRange: 0,
        radius: 0,
        skillType: 'self',
        damageType: 'physical',
        baseDamageByLevel: [0, 0, 0],
        scalingRatio: 0,
      },
    ],
    recommendedBuild: ['swift_boots', 'windtalker', 'berserkers_fury', 'haas_claws', 'malefic_roar', 'blade_of_despair'],
    spellId: 'flicker',
  },

  tigreal: {
    id: 'tigreal',
    name: 'Tigreal',
    title: 'Warrior of Dawn',
    heroClass: 'tank',
    primaryRole: 'roamer',
    avatar: '🛡️',
    color: '#eab308', // Amber
    accentColor: '#fde047',
    baseStats: {
      maxHp: 3200,
      hpRegen: 45,
      maxMana: 450,
      manaRegen: 12,
      physicalAttack: 112,
      magicPower: 0,
      physicalDefense: 28,
      magicDefense: 15,
      attackSpeed: 0.85,
      movementSpeed: 8.2,
      attackRange: 2.2, // Melee
      critChance: 0,
      critDamage: 2.0,
      cooldownReduction: 0,
      physicalLifesteal: 0,
      magicLifesteal: 0,
      physicalPenetration: 0,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 220,
      manaPerLevel: 25,
      physAtkPerLevel: 7,
      armorPerLevel: 5.5,
    },
    passive: {
      name: 'Fearless',
      description: 'Gains 1 stack of Fearless upon using a skill or taking basic attacks. At 4 stacks, Tigreal blocks the next incoming basic attack completely.',
      icon: '🛡️',
    },
    skills: [
      {
        id: 'tigreal_s1',
        name: 'Attack Wave',
        description: 'Tigreal strikes the ground with his heavy hammer, unleashing a ground shockwave that deals physical damage and slows enemies by 30%.',
        icon: '🌊',
        maxLevel: 4,
        cooldownByLevel: [7, 6.5, 6, 5.5],
        manaCostByLevel: [45, 50, 55, 60],
        castRange: 8,
        radius: 1.8,
        skillType: 'skillshot',
        damageType: 'physical',
        baseDamageByLevel: [270, 330, 390, 450],
        scalingRatio: 0.7,
        crowdControl: {
          type: 'slow',
          duration: 1.5,
          intensity: 0.3,
        },
      },
      {
        id: 'tigreal_s2',
        name: 'Sacred Hammer',
        description: 'Charges forward pushing colliding enemies with his shield, and can be recast within 4s to knock airborne enemies with an uppercut for 1s.',
        icon: '🔨',
        maxLevel: 4,
        cooldownByLevel: [12, 11, 10, 9],
        manaCostByLevel: [90, 100, 110, 120],
        castRange: 7,
        radius: 2.2,
        skillType: 'dash',
        damageType: 'physical',
        baseDamageByLevel: [220, 260, 300, 340],
        scalingRatio: 1.0,
        crowdControl: {
          type: 'knockup',
          duration: 1.0,
        },
      },
      {
        id: 'tigreal_s3',
        name: 'Implosion',
        description: 'Thrusts his sword into the earth, channeling for 1s before pulling all surrounding enemies towards him and stunning them for 1.5s.',
        icon: '🌀',
        maxLevel: 3,
        cooldownByLevel: [45, 40, 35],
        manaCostByLevel: [150, 170, 190],
        castRange: 0,
        radius: 6.0,
        skillType: 'aoe',
        damageType: 'physical',
        baseDamageByLevel: [350, 480, 600],
        scalingRatio: 1.2,
        crowdControl: {
          type: 'stun',
          duration: 1.5,
        },
      },
    ],
    recommendedBuild: ['tough_boots', 'blade_armor', 'athena_shield', 'antique_cuirass', 'dominance_ice', 'immortality'],
    spellId: 'flicker',
  },

  eudora: {
    id: 'eudora',
    name: 'Eudora',
    title: 'Lightning Weaver',
    heroClass: 'mage',
    primaryRole: 'mid_lane',
    avatar: '⚡',
    color: '#3b82f6', // Electric Blue
    accentColor: '#60a5fa',
    baseStats: {
      maxHp: 2450,
      hpRegen: 32,
      maxMana: 500,
      manaRegen: 20,
      physicalAttack: 105,
      magicPower: 0,
      physicalDefense: 16,
      magicDefense: 15,
      attackSpeed: 0.95,
      movementSpeed: 8.4,
      attackRange: 6.8,
      critChance: 0,
      critDamage: 2.0,
      cooldownReduction: 0,
      physicalLifesteal: 0,
      magicLifesteal: 0,
      physicalPenetration: 0,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 140,
      manaPerLevel: 45,
      physAtkPerLevel: 6,
      armorPerLevel: 2.8,
    },
    passive: {
      name: 'Superconductor',
      description: 'Skills inflict Superconductor on targets for 3s. Other skills consume Superconductor to amplify damage and secondary effects.',
      icon: '⚡',
    },
    skills: [
      {
        id: 'eudora_s1',
        name: 'Forked Lightning',
        description: 'Casts a fan-shaped surge of forked lightning, dealing heavy magic damage to all enemies in the cone.',
        icon: '🌩️',
        maxLevel: 4,
        cooldownByLevel: [6, 5.5, 5, 4.5],
        manaCostByLevel: [60, 68, 76, 84],
        castRange: 7.5,
        radius: 3.5,
        skillType: 'aoe',
        damageType: 'magic',
        baseDamageByLevel: [350, 450, 550, 650],
        scalingRatio: 1.5,
      },
      {
        id: 'eudora_s2',
        name: 'Ball Lightning',
        description: 'Hurls an orb of lightning at the target enemy, dealing magic damage and stunning them for 1.2s.',
        icon: '🔮',
        maxLevel: 4,
        cooldownByLevel: [10, 9.5, 9, 8.5],
        manaCostByLevel: [90, 100, 110, 120],
        castRange: 7.0,
        radius: 1.0,
        skillType: 'targeted',
        damageType: 'magic',
        baseDamageByLevel: [250, 310, 370, 430],
        scalingRatio: 0.9,
        crowdControl: {
          type: 'stun',
          duration: 1.2,
        },
      },
      {
        id: 'eudora_s3',
        name: "Thunder's Wrath",
        description: 'Summons a colossal lightning tempest over the target enemy hero, dealing devastating single-target magic damage and area shockwaves.',
        icon: '⚡',
        maxLevel: 3,
        cooldownByLevel: [34, 30, 26],
        manaCostByLevel: [130, 150, 170],
        castRange: 7.5,
        radius: 3.0,
        skillType: 'targeted',
        damageType: 'magic',
        baseDamageByLevel: [700, 950, 1200],
        scalingRatio: 2.1,
      },
    ],
    recommendedBuild: ['magic_shoes', 'genius_wand', 'lightning_truncheon', 'holy_crystal', 'divine_glaive', 'immortality'],
    spellId: 'flicker',
  },

  alucard: {
    id: 'alucard',
    name: 'Alucard',
    title: 'Demon Hunter',
    heroClass: 'fighter',
    primaryRole: 'exp_lane',
    avatar: '🗡️',
    color: '#ef4444', // Red
    accentColor: '#f87171',
    baseStats: {
      maxHp: 2850,
      hpRegen: 38,
      maxMana: 0, // Energy-free / no mana
      manaRegen: 0,
      physicalAttack: 128,
      magicPower: 0,
      physicalDefense: 22,
      magicDefense: 12,
      attackSpeed: 1.0,
      movementSpeed: 8.8,
      attackRange: 2.5,
      critChance: 0.05,
      critDamage: 2.0,
      cooldownReduction: 0,
      physicalLifesteal: 0.15, // Native high lifesteal
      magicLifesteal: 0,
      physicalPenetration: 0,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 180,
      manaPerLevel: 0,
      physAtkPerLevel: 11,
      armorPerLevel: 4.0,
    },
    passive: {
      name: 'Pursuit',
      description: 'After casting a skill, Alucard’s next basic attack allows him to dash directly to the target, dealing +20% bonus physical damage.',
      icon: '🩸',
    },
    skills: [
      {
        id: 'alucard_s1',
        name: 'Groundcleave',
        description: 'Leaps into the target area and strikes down, dealing physical damage to all enemies in the circle and slowing them by 40% for 2s.',
        icon: '💥',
        maxLevel: 4,
        cooldownByLevel: [8, 7.5, 7, 6.5],
        manaCostByLevel: [0, 0, 0, 0],
        castRange: 8,
        radius: 2.8,
        skillType: 'dash',
        damageType: 'physical',
        baseDamageByLevel: [250, 300, 350, 400],
        scalingRatio: 1.1,
        crowdControl: {
          type: 'slow',
          duration: 2.0,
          intensity: 0.4,
        },
      },
      {
        id: 'alucard_s2',
        name: 'Whirling Smash',
        description: 'Spins his heavy demon blade 360 degrees, slashing all adjacent foes for physical damage.',
        icon: '🔄',
        maxLevel: 4,
        cooldownByLevel: [5, 4.5, 4, 3.5],
        manaCostByLevel: [0, 0, 0, 0],
        castRange: 0,
        radius: 3.2,
        skillType: 'aoe',
        damageType: 'physical',
        baseDamageByLevel: [230, 275, 320, 365],
        scalingRatio: 1.2,
      },
      {
        id: 'alucard_s3',
        name: 'Fission Wave',
        description: 'Unlocks the demon seal for 8s, gaining +40% lifesteal and physical attack. Recast to release a powerful crescent energy wave.',
        icon: '⚔️',
        maxLevel: 3,
        cooldownByLevel: [30, 26, 22],
        manaCostByLevel: [0, 0, 0],
        castRange: 10,
        radius: 2.0,
        skillType: 'skillshot',
        damageType: 'physical',
        baseDamageByLevel: [400, 550, 700],
        scalingRatio: 1.5,
      },
    ],
    recommendedBuild: ['warrior_boots', 'endless_battle', 'blade_of_despair', 'haas_claws', 'malefic_roar', 'immortality'],
    spellId: 'retribution',
  },

  saber: {
    id: 'saber',
    name: 'Saber',
    title: 'Wandering Sword',
    heroClass: 'assassin',
    primaryRole: 'jungler',
    avatar: '🗡️',
    color: '#10b981', // Emerald
    accentColor: '#34d399',
    baseStats: {
      maxHp: 2600,
      hpRegen: 35,
      maxMana: 430,
      manaRegen: 16,
      physicalAttack: 135,
      magicPower: 0,
      physicalDefense: 17,
      magicDefense: 11,
      attackSpeed: 1.05,
      movementSpeed: 9.0, // Very agile
      attackRange: 2.4,
      critChance: 0.05,
      critDamage: 2.0,
      cooldownReduction: 0.05,
      physicalLifesteal: 0,
      magicLifesteal: 0,
      physicalPenetration: 15,
      magicPenetration: 0,
    },
    growthStats: {
      hpPerLevel: 155,
      manaPerLevel: 30,
      physAtkPerLevel: 11.5,
      armorPerLevel: 3.3,
    },
    passive: {
      name: "Enemy's Bane",
      description: 'Each physical attack reduces the target’s physical defense by 5 (stacks up to 5 times for 25 reduction).',
      icon: '🔪',
    },
    skills: [
      {
        id: 'saber_s1',
        name: 'Orbiting Swords',
        description: 'Releases 4 flying swords that orbit Saber, each slashing nearby enemies and shooting towards targets when Saber basic attacks.',
        icon: '🗡️',
        maxLevel: 4,
        cooldownByLevel: [9, 8.5, 8, 7.5],
        manaCostByLevel: [60, 68, 76, 84],
        castRange: 0,
        radius: 4.5,
        skillType: 'self',
        damageType: 'physical',
        baseDamageByLevel: [100, 130, 160, 190],
        scalingRatio: 0.6,
      },
      {
        id: 'saber_s2',
        name: 'Charge',
        description: 'Dashes forward swiftly dealing physical damage to enemies in the path and enhancing the next basic attack with slow and extra damage.',
        icon: '💨',
        maxLevel: 4,
        cooldownByLevel: [7, 6.5, 6, 5.5],
        manaCostByLevel: [50, 55, 60, 65],
        castRange: 6.5,
        radius: 1.5,
        skillType: 'dash',
        damageType: 'physical',
        baseDamageByLevel: [160, 200, 240, 280],
        scalingRatio: 0.8,
      },
      {
        id: 'saber_s3',
        name: 'Triple Sweep',
        description: 'Locks onto an enemy hero, leaps to knock them airborne for 1.2s, and slashes 3 times dealing catastrophic burst damage.',
        icon: '⚔️',
        maxLevel: 3,
        cooldownByLevel: [32, 28, 24],
        manaCostByLevel: [100, 115, 130],
        castRange: 6.0,
        radius: 1.0,
        skillType: 'targeted',
        damageType: 'physical',
        baseDamageByLevel: [450, 650, 850],
        scalingRatio: 2.0,
        crowdControl: {
          type: 'airborne',
          duration: 1.2,
        },
      },
    ],
    recommendedBuild: ['warrior_boots', 'blade_of_despair', 'malefic_roar', 'endless_battle', 'hunter_strike', 'immortality'],
    spellId: 'execute',
  },
};
