import type { ItemDefinition } from '../types/item';

export const ITEM_REGISTRY: Record<string, ItemDefinition> = {
  // === MOVEMENT (BOOTS) ===
  swift_boots: {
    id: 'swift_boots',
    name: 'Swift Boots',
    category: 'movement',
    tier: 2,
    cost: 710,
    icon: '👟',
    description: '+40 Movement Speed, +15% Attack Speed',
    stats: {
      movementSpeed: 1.5,
      attackSpeed: 0.15,
    },
  },
  warrior_boots: {
    id: 'warrior_boots',
    name: 'Warrior Boots',
    category: 'movement',
    tier: 2,
    cost: 720,
    icon: '👢',
    description: '+40 Movement Speed, +22 Physical Defense. Stack armor on hits.',
    stats: {
      movementSpeed: 1.5,
      physicalDefense: 22,
    },
    passive: {
      name: 'Valor',
      description: 'Physical defense increases by 5 for 3s when taking physical attacks (stacks up to 5 times).',
      effectType: 'warrior_valor',
    },
  },
  tough_boots: {
    id: 'tough_boots',
    name: 'Tough Boots',
    category: 'movement',
    tier: 2,
    cost: 700,
    icon: '🥾',
    description: '+40 Movement Speed, +22 Magic Defense. Reduces CC duration by 30%.',
    stats: {
      movementSpeed: 1.5,
      magicDefense: 22,
    },
  },
  magic_shoes: {
    id: 'magic_shoes',
    name: 'Magic Shoes',
    category: 'movement',
    tier: 2,
    cost: 710,
    icon: '👠',
    description: '+40 Movement Speed, +10% Cooldown Reduction.',
    stats: {
      movementSpeed: 1.5,
      cooldownReduction: 0.1,
    },
  },

  // === ATTACK ITEMS ===
  blade_of_despair: {
    id: 'blade_of_despair',
    name: 'Blade of Despair',
    category: 'attack',
    tier: 3,
    cost: 3010,
    icon: '🗡️',
    description: '+160 Physical Attack, +5% Movement Speed. Deals +25% damage to targets below 50% HP.',
    stats: {
      physicalAttack: 160,
      movementSpeed: 0.5,
    },
    passive: {
      name: 'Despair',
      description: 'Attacking enemy units with HP below 50% grants +25% Physical Attack for 2s.',
      effectType: 'despair',
    },
  },
  demon_hunter_sword: {
    id: 'demon_hunter_sword',
    name: 'Demon Hunter Sword',
    category: 'attack',
    tier: 3,
    cost: 2180,
    icon: '⚔️',
    description: '+35 Physical Attack, +25% Attack Speed. Basic attacks deal 8% of target current HP as bonus damage.',
    stats: {
      physicalAttack: 35,
      attackSpeed: 0.25,
      lifesteal: 0.05,
    },
    passive: {
      name: 'Devour',
      description: 'Basic attacks deal 8% of the target’s current HP as additional physical damage.',
      effectType: 'demon_hunter',
    },
  },
  berserkers_fury: {
    id: 'berserkers_fury',
    name: "Berserker's Fury",
    category: 'attack',
    tier: 3,
    cost: 2250,
    icon: '🪓',
    description: '+65 Physical Attack, +25% Crit Chance. +40% Critical Damage.',
    stats: {
      physicalAttack: 65,
      critChance: 0.25,
    },
    passive: {
      name: 'Doom',
      description: 'Critical hits grant +5% Physical Attack for 2s.',
      effectType: 'berserker_crit',
    },
  },
  windtalker: {
    id: 'windtalker',
    name: 'Windtalker',
    category: 'attack',
    tier: 3,
    cost: 1820,
    icon: '🌪️',
    description: '+40% Attack Speed, +20 Movement Speed, +10% Crit Chance. Splash magic damage on attacks.',
    stats: {
      attackSpeed: 0.4,
      movementSpeed: 0.8,
      critChance: 0.1,
    },
    passive: {
      name: 'Typhoon',
      description: 'Every 5-3s, the next basic attack unleashes a gust hitting up to 3 enemies with magic damage.',
      effectType: 'windtalker_typhoon',
    },
  },
  endless_battle: {
    id: 'endless_battle',
    name: 'Endless Battle',
    category: 'attack',
    tier: 3,
    cost: 2470,
    icon: '🔱',
    description: '+65 Physical Attack, +250 HP, +10% CDR, +10% Lifesteal, +5% Movement Speed.',
    stats: {
      physicalAttack: 65,
      hp: 250,
      cooldownReduction: 0.1,
      lifesteal: 0.1,
      movementSpeed: 0.5,
    },
  },
  haas_claws: {
    id: 'haas_claws',
    name: "Haas's Claws",
    category: 'attack',
    tier: 3,
    cost: 1810,
    icon: '🦞',
    description: '+70 Physical Attack, +20% Physical Lifesteal. Huge sustain when HP is low.',
    stats: {
      physicalAttack: 70,
      lifesteal: 0.2,
    },
  },
  malefic_roar: {
    id: 'malefic_roar',
    name: 'Malefic Roar',
    category: 'attack',
    tier: 3,
    cost: 2060,
    icon: '🔫',
    description: '+60 Physical Attack, +35% Physical Penetration. Devastates armor and turrets.',
    stats: {
      physicalAttack: 60,
      physicalPenetration: 35,
    },
  },
  hunter_strike: {
    id: 'hunter_strike',
    name: 'Hunter Strike',
    category: 'attack',
    tier: 3,
    cost: 2010,
    icon: '🎯',
    description: '+80 Physical Attack, +10% CDR, +15 Physical Penetration.',
    stats: {
      physicalAttack: 80,
      cooldownReduction: 0.1,
      physicalPenetration: 15,
    },
  },

  // === MAGIC ITEMS ===
  holy_crystal: {
    id: 'holy_crystal',
    name: 'Holy Crystal',
    category: 'magic',
    tier: 3,
    cost: 2180,
    icon: '💎',
    description: '+100 Magic Power. Passive increases total Magic Power by 21% - 35%.',
    stats: {
      magicPower: 100,
    },
    passive: {
      name: 'Mystery',
      description: 'Increases Magic Power by 21%-35% (scaling with hero level).',
      effectType: 'holy_mystery',
    },
  },
  lightning_truncheon: {
    id: 'lightning_truncheon',
    name: 'Lightning Truncheon',
    category: 'magic',
    tier: 3,
    cost: 2250,
    icon: '⚡',
    description: '+75 Magic Power, +400 Mana, +10% CDR. Periodic magic echo burst.',
    stats: {
      magicPower: 75,
      mana: 400,
      cooldownReduction: 0.1,
    },
    passive: {
      name: 'Resonate',
      description: 'Every 6s, the next skill resonates, dealing magic damage to up to 3 enemies based on max mana.',
      effectType: 'lightning_echo',
    },
  },
  genius_wand: {
    id: 'genius_wand',
    name: 'Genius Wand',
    category: 'magic',
    tier: 3,
    cost: 2000,
    icon: '🪄',
    description: '+75 Magic Power, +5% Movement Speed, +10 Magic Penetration. Shreds enemy magic defense on hit.',
    stats: {
      magicPower: 75,
      movementSpeed: 0.5,
      magicPenetration: 10,
    },
  },
  divine_glaive: {
    id: 'divine_glaive',
    name: 'Divine Glaive',
    category: 'magic',
    tier: 3,
    cost: 1970,
    icon: '✨',
    description: '+65 Magic Power, +40% Magic Penetration. Cuts through heavy magic defense.',
    stats: {
      magicPower: 65,
      magicPenetration: 40,
    },
  },
  concentrated_energy: {
    id: 'concentrated_energy',
    name: 'Concentrated Energy',
    category: 'magic',
    tier: 3,
    cost: 2020,
    icon: '🔮',
    description: '+70 Magic Power, +700 HP, +25% Magic Lifesteal.',
    stats: {
      magicPower: 70,
      hp: 700,
    },
  },

  // === DEFENSE ITEMS ===
  immortality: {
    id: 'immortality',
    name: 'Immortality',
    category: 'defense',
    tier: 3,
    cost: 2120,
    icon: '🕊️',
    description: '+800 HP, +30 Physical Defense. Resurrects 2.5s after death with 16% HP and a shield.',
    stats: {
      hp: 800,
      physicalDefense: 30,
    },
    passive: {
      name: 'Immortal',
      description: 'Resurrects 2.5s after death with 16% Max HP and a 220-1200 shield. 210s cooldown.',
      effectType: 'immortality_resurrect',
    },
  },
  blade_armor: {
    id: 'blade_armor',
    name: 'Blade Armor',
    category: 'defense',
    tier: 3,
    cost: 1960,
    icon: '🛡️',
    description: '+90 Physical Defense, +20% Crit Damage Reduction. Reflects 20% of basic attack damage back to attacker.',
    stats: {
      physicalDefense: 90,
    },
    passive: {
      name: 'Bladed Armor',
      description: 'When struck by a basic attack, reflects 20% of the damage taken back to the attacker.',
      effectType: 'blade_armor_reflect',
    },
  },
  athena_shield: {
    id: 'athena_shield',
    name: "Athena's Shield",
    category: 'defense',
    tier: 3,
    cost: 2150,
    icon: '🔮',
    description: '+900 HP, +62 Magic Defense, +2 HP Regen. Grants 25% magic damage reduction shield upon taking magic hit.',
    stats: {
      hp: 900,
      magicDefense: 62,
    },
    passive: {
      name: 'Shield',
      description: 'Reduces incoming magic damage by 25% for 3s upon taking magic damage.',
      effectType: 'athena_shield',
    },
  },
  antique_cuirass: {
    id: 'antique_cuirass',
    name: 'Antique Cuirass',
    category: 'defense',
    tier: 3,
    cost: 2170,
    icon: '🦺',
    description: '+920 HP, +54 Physical Defense, +4 HP Regen. Reduces attacker’s Physical Attack by 8% on hit.',
    stats: {
      hp: 920,
      physicalDefense: 54,
    },
  },
  dominance_ice: {
    id: 'dominance_ice',
    name: 'Dominance Ice',
    category: 'defense',
    tier: 3,
    cost: 2010,
    icon: '❄️',
    description: '+500 Mana, +70 Physical Defense, +5% Movement Speed, +10% CDR. Reduces nearby enemy HP regen & attack speed.',
    stats: {
      mana: 500,
      physicalDefense: 70,
      movementSpeed: 0.5,
      cooldownReduction: 0.1,
    },
  },
};
