import type {
  TurretEntity,
  BaseCoreEntity,
  JungleCampEntity,
  BushZone,
  MapWaypoint,
} from '../types/map';

export const MAP_BOUNDS = {
  minX: -85,
  maxX: 85,
  minZ: -85,
  maxZ: 85,
  size: 170,
};

export const BASE_SPAWNS = {
  blue: { x: -72, y: 0, z: 72 },
  red: { x: 72, y: 0, z: -72 },
};

// 3 Lanes Waypoints for Minion wave marching
export const LANE_WAYPOINTS: Record<
  'top' | 'mid' | 'bot',
  { blue: MapWaypoint[]; red: MapWaypoint[] }
> = {
  top: {
    blue: [
      { x: -70, y: 0, z: 65 },
      { x: -70, y: 0, z: 35 },
      { x: -70, y: 0, z: 0 },
      { x: -70, y: 0, z: -40 },
      { x: -70, y: 0, z: -68 },
      { x: -40, y: 0, z: -68 },
      { x: 0, y: 0, z: -68 },
      { x: 40, y: 0, z: -68 },
      { x: 68, y: 0, z: -68 },
    ],
    red: [
      { x: 68, y: 0, z: -68 },
      { x: 40, y: 0, z: -68 },
      { x: 0, y: 0, z: -68 },
      { x: -40, y: 0, z: -68 },
      { x: -70, y: 0, z: -68 },
      { x: -70, y: 0, z: -40 },
      { x: -70, y: 0, z: 0 },
      { x: -70, y: 0, z: 35 },
      { x: -70, y: 0, z: 65 },
    ],
  },
  mid: {
    blue: [
      { x: -65, y: 0, z: 65 },
      { x: -45, y: 0, z: 45 },
      { x: -25, y: 0, z: 25 },
      { x: 0, y: 0, z: 0 },
      { x: 25, y: 0, z: -25 },
      { x: 45, y: 0, z: -45 },
      { x: 65, y: 0, z: -65 },
    ],
    red: [
      { x: 65, y: 0, z: -65 },
      { x: 45, y: 0, z: -45 },
      { x: 25, y: 0, z: -25 },
      { x: 0, y: 0, z: 0 },
      { x: -25, y: 0, z: 25 },
      { x: -45, y: 0, z: 45 },
      { x: -65, y: 0, z: 65 },
    ],
  },
  bot: {
    blue: [
      { x: -65, y: 0, z: 70 },
      { x: -40, y: 0, z: 70 },
      { x: 0, y: 0, z: 70 },
      { x: 40, y: 0, z: 70 },
      { x: 68, y: 0, z: 70 },
      { x: 68, y: 0, z: 40 },
      { x: 68, y: 0, z: 0 },
      { x: 68, y: 0, z: -40 },
      { x: 68, y: 0, z: -65 },
    ],
    red: [
      { x: 68, y: 0, z: -65 },
      { x: 68, y: 0, z: -40 },
      { x: 68, y: 0, z: 0 },
      { x: 68, y: 0, z: 40 },
      { x: 68, y: 0, z: 70 },
      { x: 40, y: 0, z: 70 },
      { x: 0, y: 0, z: 70 },
      { x: -40, y: 0, z: 70 },
      { x: -65, y: 0, z: 70 },
    ],
  },
};

export const INITIAL_TURRETS: TurretEntity[] = [
  // --- BLUE TURRETS ---
  // Top
  {
    id: 'blue_top_outer',
    lane: 'top',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: -70, y: 0, z: -10 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_top_inner',
    lane: 'top',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: -70, y: 0, z: 25 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_top_base',
    lane: 'top',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: -70, y: 0, z: 52 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  // Mid
  {
    id: 'blue_mid_outer',
    lane: 'mid',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: -20, y: 0, z: 20 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_mid_inner',
    lane: 'mid',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: -38, y: 0, z: 38 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_mid_base',
    lane: 'mid',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: -54, y: 0, z: 54 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  // Bot
  {
    id: 'blue_bot_outer',
    lane: 'bot',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: 10, y: 0, z: 70 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_bot_inner',
    lane: 'bot',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: -25, y: 0, z: 70 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'blue_bot_base',
    lane: 'bot',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: -52, y: 0, z: 70 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },

  // --- RED TURRETS ---
  // Top
  {
    id: 'red_top_outer',
    lane: 'top',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: -10, y: 0, z: -68 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_top_inner',
    lane: 'top',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: 25, y: 0, z: -68 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_top_base',
    lane: 'top',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: 52, y: 0, z: -68 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  // Mid
  {
    id: 'red_mid_outer',
    lane: 'mid',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: 20, y: 0, z: -20 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_mid_inner',
    lane: 'mid',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: 38, y: 0, z: -38 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_mid_base',
    lane: 'mid',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: 54, y: 0, z: -54 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  // Bot
  {
    id: 'red_bot_outer',
    lane: 'bot',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 220,
    physicalDefense: 35,
    range: 13,
    position: { x: 68, y: 0, z: 10 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_bot_inner',
    lane: 'bot',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 250,
    physicalDefense: 40,
    range: 13,
    position: { x: 68, y: 0, z: -25 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
  {
    id: 'red_bot_base',
    lane: 'bot',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 290,
    physicalDefense: 45,
    range: 13,
    position: { x: 68, y: 0, z: -52 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
  },
];

export const INITIAL_BASE_CORES: Record<'blue' | 'red', BaseCoreEntity> = {
  blue: {
    id: 'blue_nexus_core',
    team: 'blue',
    maxHp: 10000,
    currentHp: 10000,
    physicalAttack: 350,
    range: 15,
    position: { x: -68, y: 0, z: 68 },
    targetEntityId: null,
    isDestroyed: false,
  },
  red: {
    id: 'red_nexus_core',
    team: 'red',
    maxHp: 10000,
    currentHp: 10000,
    physicalAttack: 350,
    range: 15,
    position: { x: 68, y: 0, z: -68 },
    targetEntityId: null,
    isDestroyed: false,
  },
};

export const INITIAL_JUNGLE_CAMPS: JungleCampEntity[] = [
  // Blue Buffs
  {
    id: 'camp_blue_buff_blue',
    campType: 'blue_buff',
    name: 'Statued Chocker (Blue Buff)',
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 120,
    attackRange: 3.5,
    position: { x: -45, y: 0, z: 12 },
    spawnPosition: { x: -45, y: 0, z: 12 },
    leashRadius: 10,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 140,
    expReward: 160,
    buffType: 'blue',
  },
  {
    id: 'camp_blue_buff_red',
    campType: 'blue_buff',
    name: 'Statued Chocker (Blue Buff)',
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 120,
    attackRange: 3.5,
    position: { x: 45, y: 0, z: -12 },
    spawnPosition: { x: 45, y: 0, z: -12 },
    leashRadius: 10,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 140,
    expReward: 160,
    buffType: 'blue',
  },

  // Red Buffs
  {
    id: 'camp_red_buff_blue',
    campType: 'red_buff',
    name: 'Fiend Beast (Red Buff)',
    maxHp: 4000,
    currentHp: 4000,
    physicalAttack: 130,
    attackRange: 3.5,
    position: { x: -12, y: 0, z: 45 },
    spawnPosition: { x: -12, y: 0, z: 45 },
    leashRadius: 10,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 140,
    expReward: 160,
    buffType: 'red',
  },
  {
    id: 'camp_red_buff_red',
    campType: 'red_buff',
    name: 'Fiend Beast (Red Buff)',
    maxHp: 4000,
    currentHp: 4000,
    physicalAttack: 130,
    attackRange: 3.5,
    position: { x: 12, y: 0, z: -45 },
    spawnPosition: { x: 12, y: 0, z: -45 },
    leashRadius: 10,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 140,
    expReward: 160,
    buffType: 'red',
  },

  // Minor Creeps
  {
    id: 'camp_rock_blue',
    campType: 'rock_golem',
    name: 'Rock Golem',
    maxHp: 2200,
    currentHp: 2200,
    physicalAttack: 80,
    attackRange: 3.0,
    position: { x: -48, y: 0, z: -18 },
    spawnPosition: { x: -48, y: 0, z: -18 },
    leashRadius: 8,
    respawnTimeSeconds: 70,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 75,
    expReward: 90,
  },
  {
    id: 'camp_lizard_blue',
    campType: 'scaled_lizard',
    name: 'Scaled Lizard',
    maxHp: 2000,
    currentHp: 2000,
    physicalAttack: 75,
    attackRange: 3.0,
    position: { x: -20, y: 0, z: 52 },
    spawnPosition: { x: -20, y: 0, z: 52 },
    leashRadius: 8,
    respawnTimeSeconds: 70,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 75,
    expReward: 90,
  },

  // Epic River Boss: Turtle (First 8 mins) -> Lord (after 8 mins)
  {
    id: 'camp_turtle',
    campType: 'turtle',
    name: 'The Turtle',
    maxHp: 8500,
    currentHp: 8500,
    physicalAttack: 190,
    attackRange: 4.5,
    position: { x: -18, y: 0, z: -18 },
    spawnPosition: { x: -18, y: 0, z: -18 },
    leashRadius: 12,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 250,
    expReward: 300,
    buffType: 'turtle',
  },
  {
    id: 'camp_lord',
    campType: 'lord',
    name: 'The Sanctuary Lord',
    maxHp: 16000,
    currentHp: 16000,
    physicalAttack: 320,
    attackRange: 5.0,
    position: { x: 18, y: 0, z: 18 },
    spawnPosition: { x: 18, y: 0, z: 18 },
    leashRadius: 12,
    respawnTimeSeconds: 180,
    remainingRespawnTimer: 480, // Spawns at 8 minutes (480s)
    isAlive: false,
    targetEntityId: null,
    goldReward: 400,
    expReward: 500,
    buffType: 'lord',
  },
];

export const BUSH_ZONES: BushZone[] = [
  // River Center Bushes
  { id: 'bush_river_mid_left', minX: -10, maxX: -4, minZ: -4, maxZ: 8, center: { x: -7, y: 0, z: 2 } },
  { id: 'bush_river_mid_right', minX: 4, maxX: 10, minZ: -8, maxZ: 4, center: { x: 7, y: 0, z: -2 } },
  // Side Lane Bushes
  { id: 'bush_top_river', minX: -45, maxX: -35, minZ: -48, maxZ: -40, center: { x: -40, y: 0, z: -44 } },
  { id: 'bush_bot_river', minX: 35, maxX: 45, minZ: 40, maxZ: 48, center: { x: 40, y: 0, z: 44 } },
  { id: 'bush_top_lane', minX: -74, maxX: -66, minZ: -20, maxZ: -12, center: { x: -70, y: 0, z: -16 } },
  { id: 'bush_bot_lane', minX: 12, maxX: 20, minZ: 66, maxZ: 74, center: { x: 16, y: 0, z: 70 } },
  // Buff Bushes
  { id: 'bush_blue_buff_blue', minX: -52, maxX: -46, minZ: 18, maxZ: 26, center: { x: -49, y: 0, z: 22 } },
  { id: 'bush_red_buff_blue', minX: -26, maxX: -18, minZ: 46, maxZ: 52, center: { x: -22, y: 0, z: 49 } },
  { id: 'bush_blue_buff_red', minX: 46, maxX: 52, minZ: -26, maxZ: -18, center: { x: 49, y: 0, z: -22 } },
  { id: 'bush_red_buff_red', minX: 18, maxX: 26, minZ: -52, maxZ: -46, center: { x: 22, y: 0, z: -49 } },
];
