import type {
  TurretEntity,
  BaseCoreEntity,
  JungleCampEntity,
  BushZone,
  MapWaypoint,
} from '../types/map';

export const MAP_BOUNDS = {
  minX: -55,
  maxX: 55,
  minZ: -55,
  maxZ: 55,
  size: 110,
};

export const BASE_SPAWNS = {
  blue: { x: -42, y: 0, z: 42 },
  red: { x: 42, y: 0, z: -42 },
};

// 3 Lanes Waypoints for Minion wave marching (tight, balanced 110x110 map)
export const LANE_WAYPOINTS: Record<
  'top' | 'mid' | 'bot',
  { blue: MapWaypoint[]; red: MapWaypoint[] }
> = {
  top: {
    blue: [
      { x: -40, y: 0, z: 38 },
      { x: -40, y: 0, z: 26 },
      { x: -40, y: 0, z: 2 },
      { x: -40, y: 0, z: -22 },
      { x: -40, y: 0, z: -40 },
      { x: -22, y: 0, z: -40 },
      { x: 2, y: 0, z: -40 },
      { x: 26, y: 0, z: -40 },
      { x: 38, y: 0, z: -40 },
    ],
    red: [
      { x: 38, y: 0, z: -40 },
      { x: 26, y: 0, z: -40 },
      { x: 2, y: 0, z: -40 },
      { x: -22, y: 0, z: -40 },
      { x: -40, y: 0, z: -40 },
      { x: -40, y: 0, z: -22 },
      { x: -40, y: 0, z: 2 },
      { x: -40, y: 0, z: 26 },
      { x: -40, y: 0, z: 38 },
    ],
  },
  mid: {
    blue: [
      { x: -38, y: 0, z: 38 },
      { x: -28, y: 0, z: 28 },
      { x: -18, y: 0, z: 18 },
      { x: -9, y: 0, z: 9 },
      { x: 0, y: 0, z: 0 },
      { x: 9, y: 0, z: -9 },
      { x: 18, y: 0, z: -18 },
      { x: 28, y: 0, z: -28 },
      { x: 38, y: 0, z: -38 },
    ],
    red: [
      { x: 38, y: 0, z: -38 },
      { x: 28, y: 0, z: -28 },
      { x: 18, y: 0, z: -18 },
      { x: 9, y: 0, z: -9 },
      { x: 0, y: 0, z: 0 },
      { x: -9, y: 0, z: 9 },
      { x: -18, y: 0, z: 18 },
      { x: -28, y: 0, z: 28 },
      { x: -38, y: 0, z: 38 },
    ],
  },
  bot: {
    blue: [
      { x: -38, y: 0, z: 40 },
      { x: -26, y: 0, z: 40 },
      { x: -2, y: 0, z: 40 },
      { x: 22, y: 0, z: 40 },
      { x: 40, y: 0, z: 40 },
      { x: 40, y: 0, z: 22 },
      { x: 40, y: 0, z: -2 },
      { x: 40, y: 0, z: -26 },
      { x: 40, y: 0, z: -38 },
    ],
    red: [
      { x: 40, y: 0, z: -38 },
      { x: 40, y: 0, z: -26 },
      { x: 40, y: 0, z: -2 },
      { x: 40, y: 0, z: 22 },
      { x: 40, y: 0, z: 40 },
      { x: 22, y: 0, z: 40 },
      { x: -2, y: 0, z: 40 },
      { x: -26, y: 0, z: 40 },
      { x: -38, y: 0, z: 40 },
    ],
  },
};

export const INITIAL_TURRETS: TurretEntity[] = [
  // --- BLUE TURRETS ---
  // Top Lane (along x = -40)
  {
    id: 'blue_top_outer',
    lane: 'top',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: -40, y: 0, z: -22 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_top_inner',
    lane: 'top',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: -40, y: 0, z: 2 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_top_base',
    lane: 'top',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: -40, y: 0, z: 26 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },

  // Mid Lane (along x = -z)
  {
    id: 'blue_mid_outer',
    lane: 'mid',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: -9, y: 0, z: 9 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_mid_inner',
    lane: 'mid',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: -18, y: 0, z: 18 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_mid_base',
    lane: 'mid',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: -28, y: 0, z: 28 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },

  // Bot Lane (along z = 40)
  {
    id: 'blue_bot_outer',
    lane: 'bot',
    tier: 'outer',
    team: 'blue',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: 22, y: 0, z: 40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_bot_inner',
    lane: 'bot',
    tier: 'inner',
    team: 'blue',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: -2, y: 0, z: 40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'blue_bot_base',
    lane: 'bot',
    tier: 'base',
    team: 'blue',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: -26, y: 0, z: 40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },

  // --- RED TURRETS ---
  // Top Lane (along z = -40)
  {
    id: 'red_top_outer',
    lane: 'top',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: -22, y: 0, z: -40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_top_inner',
    lane: 'top',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: 2, y: 0, z: -40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_top_base',
    lane: 'top',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: 26, y: 0, z: -40 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },

  // Mid Lane (along x = -z)
  {
    id: 'red_mid_outer',
    lane: 'mid',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: 9, y: 0, z: -9 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_mid_inner',
    lane: 'mid',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: 18, y: 0, z: -18 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_mid_base',
    lane: 'mid',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: 28, y: 0, z: -28 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },

  // Bot Lane (along x = 40)
  {
    id: 'red_bot_outer',
    lane: 'bot',
    tier: 'outer',
    team: 'red',
    maxHp: 4500,
    currentHp: 4500,
    physicalAttack: 260,
    physicalDefense: 35,
    range: 11,
    position: { x: 40, y: 0, z: 22 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: true,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_bot_inner',
    lane: 'bot',
    tier: 'inner',
    team: 'red',
    maxHp: 5500,
    currentHp: 5500,
    physicalAttack: 290,
    physicalDefense: 40,
    range: 11,
    position: { x: 40, y: 0, z: -2 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
  {
    id: 'red_bot_base',
    lane: 'bot',
    tier: 'base',
    team: 'red',
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 320,
    physicalDefense: 45,
    range: 11,
    position: { x: 40, y: 0, z: -26 },
    targetEntityId: null,
    laserProgress: 0,
    isDestroyed: false,
    hasShieldPlating: false,
    consecutiveHitsOnTarget: 0,
    attackCooldown: 0,
  },
];

export const INITIAL_BASE_CORES: Record<'blue' | 'red', BaseCoreEntity> = {
  blue: {
    id: 'blue_base_core',
    team: 'blue',
    maxHp: 9000,
    currentHp: 9000,
    physicalAttack: 380,
    range: 14,
    position: { x: -42, y: 0, z: 42 },
    targetEntityId: null,
    isDestroyed: false,
  },
  red: {
    id: 'red_base_core',
    team: 'red',
    maxHp: 9000,
    currentHp: 9000,
    physicalAttack: 380,
    range: 14,
    position: { x: 42, y: 0, z: -42 },
    targetEntityId: null,
    isDestroyed: false,
  },
};

export const INITIAL_JUNGLE_CAMPS: JungleCampEntity[] = [
  // Turtle (River North-West)
  {
    id: 'camp_turtle',
    campType: 'turtle',
    name: 'Ancient Turtle',
    position: { x: -12, y: 0, z: -12 },
    spawnPosition: { x: -12, y: 0, z: -12 },
    maxHp: 6500,
    currentHp: 6500,
    physicalAttack: 120,
    attackRange: 3.5,
    leashRadius: 12,
    respawnTimeSeconds: 120,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 160,
    expReward: 250,
    buffType: 'turtle',
  },
  // Lord (River South-East)
  {
    id: 'camp_lord',
    campType: 'lord',
    name: 'Sanctuary Lord',
    position: { x: 12, y: 0, z: 12 },
    spawnPosition: { x: 12, y: 0, z: 12 },
    maxHp: 14000,
    currentHp: 14000,
    physicalAttack: 280,
    attackRange: 4.0,
    leashRadius: 14,
    respawnTimeSeconds: 240,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 350,
    expReward: 500,
    buffType: 'lord',
  },
  // Blue Team Blue Buff
  {
    id: 'camp_blue_buff_blue',
    campType: 'blue_buff',
    name: 'Thunder Golem',
    position: { x: -28, y: 0, z: 14 },
    spawnPosition: { x: -28, y: 0, z: 14 },
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 95,
    attackRange: 2.5,
    leashRadius: 10,
    respawnTimeSeconds: 75,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 85,
    expReward: 120,
    buffType: 'blue',
  },
  // Blue Team Red Buff
  {
    id: 'camp_red_buff_blue',
    campType: 'red_buff',
    name: 'Crimson Fiend',
    position: { x: -14, y: 0, z: 28 },
    spawnPosition: { x: -14, y: 0, z: 28 },
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 105,
    attackRange: 2.5,
    leashRadius: 10,
    respawnTimeSeconds: 75,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 85,
    expReward: 120,
    buffType: 'red',
  },
  // Red Team Blue Buff
  {
    id: 'camp_blue_buff_red',
    campType: 'blue_buff',
    name: 'Thunder Golem',
    position: { x: 28, y: 0, z: -14 },
    spawnPosition: { x: 28, y: 0, z: -14 },
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 95,
    attackRange: 2.5,
    leashRadius: 10,
    respawnTimeSeconds: 75,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 85,
    expReward: 120,
    buffType: 'blue',
  },
  // Red Team Red Buff
  {
    id: 'camp_red_buff_red',
    campType: 'red_buff',
    name: 'Crimson Fiend',
    position: { x: 14, y: 0, z: -28 },
    spawnPosition: { x: 14, y: 0, z: -28 },
    maxHp: 3800,
    currentHp: 3800,
    physicalAttack: 105,
    attackRange: 2.5,
    leashRadius: 10,
    respawnTimeSeconds: 75,
    remainingRespawnTimer: 0,
    isAlive: true,
    targetEntityId: null,
    goldReward: 85,
    expReward: 120,
    buffType: 'red',
  },
];

export const BUSH_ZONES: BushZone[] = [
  // River Center Bushes
  { id: 'bush_river_mid_left', minX: -8, maxX: -4, minZ: -3, maxZ: 5, center: { x: -6, y: 0, z: 1 } },
  { id: 'bush_river_mid_right', minX: 4, maxX: 8, minZ: -5, maxZ: 3, center: { x: 6, y: 0, z: -1 } },
  // Side Lane River Bushes
  { id: 'bush_top_river', minX: -26, maxX: -20, minZ: -30, maxZ: -24, center: { x: -23, y: 0, z: -27 } },
  { id: 'bush_bot_river', minX: 20, maxX: 26, minZ: 24, maxZ: 30, center: { x: 23, y: 0, z: 27 } },
  // Lane Ambush Bushes
  { id: 'bush_top_lane', minX: -43, maxX: -37, minZ: -14, maxZ: -8, center: { x: -40, y: 0, z: -11 } },
  { id: 'bush_bot_lane', minX: 8, maxX: 14, minZ: 37, maxZ: 43, center: { x: 11, y: 0, z: 40 } },
  // Jungle Camp Bushes
  { id: 'bush_blue_buff_blue', minX: -32, maxX: -26, minZ: 10, maxZ: 16, center: { x: -29, y: 0, z: 13 } },
  { id: 'bush_red_buff_blue', minX: -16, maxX: -10, minZ: 26, maxZ: 32, center: { x: -13, y: 0, z: 29 } },
  { id: 'bush_blue_buff_red', minX: 26, maxX: 32, minZ: -16, maxZ: -10, center: { x: 29, y: 0, z: -13 } },
  { id: 'bush_red_buff_red', minX: 10, maxX: 16, minZ: -32, maxZ: -26, center: { x: 13, y: 0, z: -29 } },
];
