import type { BuildingDefinition } from '../types';

export const INITIAL_BUILDINGS_CATALOG: BuildingDefinition[] = [
  {
    id: 'headquarters',
    name: 'Headquarters',
    description: 'Central Command Center of your military base. Unlocks high-tier facilities and houses war staff.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 0, wood: 0, oil: 0 },
    requiredLevel: 1,
    constructionTimeSeconds: 5,
    populationBonus: 40,
    color: '#3b82f6',
    accentColor: '#1d4ed8',
    icon: 'ShieldAlert',
  },
  {
    id: 'town_hall',
    name: 'Military Town Hall',
    description: 'Administers base operations and civic infrastructure. Raises maximum population capacity by +50.',
    category: 'community',
    width: 3,
    height: 3,
    cost: { coins: 500, wood: 200 },
    requiredLevel: 2,
    constructionTimeSeconds: 15,
    populationBonus: 50,
    color: '#8b5cf6',
    accentColor: '#6d28d9',
    icon: 'Building2',
  },
  {
    id: 'commander_cottage',
    name: 'Officer Cottage',
    description: 'Comfortable housing for military personnel and logistics crew. Generates 60 coins and houses 15 recruits.',
    category: 'residential',
    width: 2,
    height: 2,
    cost: { coins: 140, wood: 60 },
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    production: {
      resource: 'coins',
      amount: 60,
      intervalSeconds: 45,
    },
    populationCapacity: 15,
    color: '#ea580c',
    accentColor: '#9a3412',
    icon: 'Home',
  },
  {
    id: 'officer_villa',
    name: 'Staff Quarters Villa',
    description: 'Spacious residential quarters for senior officer corps. Generates 140 coins and houses 30 recruits.',
    category: 'residential',
    width: 2,
    height: 2,
    cost: { coins: 350, wood: 140, oil: 30 },
    requiredLevel: 3,
    constructionTimeSeconds: 12,
    production: {
      resource: 'coins',
      amount: 140,
      intervalSeconds: 90,
    },
    populationCapacity: 30,
    color: '#f97316',
    accentColor: '#c2410c',
    icon: 'Home',
  },
  {
    id: 'tent_barracks',
    name: 'Military Barracks',
    description: 'Recruits and houses infantry divisions and frontline field artillery.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 150, wood: 50 },
    requiredLevel: 1,
    constructionTimeSeconds: 8,
    color: '#15803d',
    accentColor: '#166534',
    icon: 'Tent',
  },
  {
    id: 'tank_factory',
    name: 'Armor Foundry',
    description: 'Heavy manufacturing bay for main battle tanks, armored transports, and motorized divisions.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 350, wood: 120, oil: 60 },
    requiredLevel: 2,
    constructionTimeSeconds: 15,
    color: '#475569',
    accentColor: '#334155',
    icon: 'Wrench',
  },
  {
    id: 'hangar_airfield',
    name: 'Airfield & Hangar',
    description: 'Deploys supersonic jet fighters and stealth bombers for surgical tactical air strikes.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 650, wood: 200, oil: 150 },
    requiredLevel: 3,
    constructionTimeSeconds: 25,
    color: '#0284c7',
    accentColor: '#0369a1',
    icon: 'Plane',
  },
  {
    id: 'naval_shipyard',
    name: 'Naval Port & Shipyard',
    description: 'Constructs coastal patrol gunboats and missile destroyers on coastal shorelines.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 800, wood: 300, oil: 200 },
    requiredLevel: 4,
    constructionTimeSeconds: 30,
    isCoastal: true,
    color: '#0891b2',
    accentColor: '#0e7490',
    icon: 'Anchor',
  },
  {
    id: 'lumber_mill',
    name: 'Lumber Mill',
    description: 'Harvests native timber from surrounding forests to provide construction materials over time.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 100 },
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    production: {
      resource: 'wood',
      amount: 45,
      intervalSeconds: 30,
    },
    color: '#854d0e',
    accentColor: '#713f12',
    icon: 'Trees',
  },
  {
    id: 'gold_mine',
    name: 'Gold Treasury',
    description: 'Mints currency and stores strategic gold reserves for island expansion.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { wood: 80 },
    requiredLevel: 1,
    constructionTimeSeconds: 8,
    production: {
      resource: 'coins',
      amount: 80,
      intervalSeconds: 40,
    },
    color: '#eab308',
    accentColor: '#ca8a04',
    icon: 'Coins',
  },
  {
    id: 'oil_refinery',
    name: 'Fuel Refinery',
    description: 'Pumps petroleum and produces synthetic jet fuels and tank propellant.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 250, wood: 100 },
    requiredLevel: 2,
    constructionTimeSeconds: 12,
    production: {
      resource: 'oil',
      amount: 35,
      intervalSeconds: 60,
    },
    color: '#06b6d4',
    accentColor: '#0891b2',
    icon: 'Fuel',
  },
  {
    id: 'guard_tower',
    name: 'Patriot Defense Tower',
    description: 'Perimeter automated turret armed with surface-to-air radar missiles and searchlights.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 180, wood: 60, oil: 25 },
    requiredLevel: 2,
    constructionTimeSeconds: 8,
    defenseScore: 45,
    color: '#dc2626',
    accentColor: '#b91c1c',
    icon: 'Crosshair',
  },
  {
    id: 'asphalt_road',
    name: 'Supply Road',
    description: 'Paved military logistics thoroughfare connecting structures across your island base.',
    category: 'infrastructure',
    width: 1,
    height: 1,
    cost: { coins: 10 },
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    color: '#334155',
    accentColor: '#1e293b',
    icon: 'Maximize2',
  },
  {
    id: 'sandbag_wall',
    name: 'Fortified Sandbags',
    description: 'Reinforced defensive perimeter barrier absorbing explosive ordnance.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 25, wood: 15 },
    requiredLevel: 1,
    constructionTimeSeconds: 2,
    defenseScore: 15,
    color: '#d97706',
    accentColor: '#92400e',
    icon: 'Shield',
  },
];
