import type { CampaignSector } from '../types';

export const CAMPAIGN_SECTORS: CampaignSector[] = [
  {
    id: 'sector_1',
    name: 'Sector 1: Outer Atoll',
    subtitle: 'Raven Syndicate Recon Vanguard',
    enemyCommander: 'Raven Scout Captain',
    difficulty: 1,
    rewards: { coins: 500, oil: 60, xp: 220, rareMaterial: 'steel' },
    isUnlocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_2',
    name: 'Sector 2: Iron Shallows',
    subtitle: 'Amphibious Armor & Patrol Boats',
    enemyCommander: 'Commander Vane',
    difficulty: 2,
    rewards: { coins: 850, oil: 110, xp: 380, rareMaterial: 'aluminum' },
    isUnlocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_3',
    name: 'Sector 3: Razor Ridge',
    subtitle: 'Fortified Howitzer Batteries',
    enemyCommander: 'Colonel Briggs',
    difficulty: 3,
    rewards: { coins: 1200, oil: 160, xp: 550, rareMaterial: 'rubber' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_4',
    name: 'Sector 4: Black Sky Airfield',
    subtitle: 'Raven Interceptor Squadron',
    enemyCommander: 'Major Drake',
    difficulty: 4,
    rewards: { coins: 1800, oil: 240, xp: 750, rareMaterial: 'copper' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_5',
    name: 'Sector 5: Fortress Castor',
    subtitle: 'General Castor Dreadnought Citadel (BOSS)',
    enemyCommander: 'General Castor (Supreme Raven Leader)',
    difficulty: 5,
    rewards: { coins: 3500, oil: 500, xp: 1500, rareMaterial: 'microchips' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
];
