import type { Quest } from '../types';

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_hq_barracks',
    title: 'Fortify the Perimeter',
    description: 'The Raven Syndicate has occupied neighboring islands. Construct a Military Barracks to mobilize troops.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Commander, welcome to your new island command station! Raven Syndicate forces are scouting our perimeter.',
      'Construct a Military Barracks immediately so we can recruit vanguard riflemen for defense.',
    ],
    targetType: 'build',
    targetKey: 'tent_barracks',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 250, wood: 100, xp: 120, energy: 5 },
  },
  {
    id: 'quest_clear_wilderness',
    title: 'Reclaim Island Ground',
    description: 'Clear a wild jungle tree or granite boulder to expand our buildable island territory and gather materials.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Our base expansion is blocked by overgrown jungle and debris.',
      'Click on any wild tree or boulder in the outskirts to clear it with 1 energy and reclaim the ground!',
    ],
    targetType: 'clear',
    targetKey: 'any',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 200, wood: 100, xp: 110 },
  },
  {
    id: 'quest_recruit_squad',
    title: 'Mobilize the Vanguard',
    description: 'Open your Barracks and recruit 2 Vanguard Riflemen to fortify your Army Reserve.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'A barracks without trained soldiers is just canvas in the wind!',
      'Click your barracks, open the recruitment depot, and train 2 riflemen into your army reserve.',
    ],
    targetType: 'train',
    targetKey: 'rifleman',
    targetCount: 2,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 300, oil: 40, xp: 150 },
  },
  {
    id: 'quest_visit_foley',
    title: 'Allied Reconnaissance',
    description: 'Visit Major Foley’s base from the Allies dock and assist his installations to earn Honor points.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'We are stronger together, Commander. Check the Allies dock at the bottom of your screen.',
      'Visit my forward island base and assist my operations to earn valuable Honor points!',
    ],
    targetType: 'visit',
    targetKey: 'ally_major_foley',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 350, honor: 40, xp: 180 },
  },
  {
    id: 'quest_first_blood',
    title: 'Repel the Raven Scout',
    description: 'Deploy your squad in Sector 1 of the Campaign Map and eliminate the Raven Syndicate recon vanguard.',
    advisorName: 'General Castor',
    advisorAvatar: 'general_castor',
    dialogue: [
      'Alert! A Raven patrol is probing our perimeter at Sector 1.',
      'Take command of our tactical squad, exploit unit weaknesses, and secure victory!',
    ],
    targetType: 'combat',
    targetKey: 'sector_1',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 500, oil: 80, xp: 250, energy: 10 },
  },
];
