import type { UnitDefinition } from '../types';

export const COMBAT_UNITS_CATALOG: UnitDefinition[] = [
  {
    id: 'rifleman',
    name: 'Vanguard Rifleman',
    unitClass: 'infantry',
    hp: 120,
    maxHp: 120,
    attackPower: 38,
    speed: 70,
    criticalChance: 0.15,
    strongAgainst: 'artillery',
    weakAgainst: 'armor',
    trainingCost: { coins: 80, population: 1 },
    trainingTimeSeconds: 10,
    buildingSourceId: 'tent_barracks',
    icon: 'UserCheck',
    description: 'Fast mobile troopers. Closes in quickly to neutralize artillery emplacements.',
  },
  {
    id: 'commando',
    name: 'Special Forces Commando',
    unitClass: 'infantry',
    hp: 165,
    maxHp: 165,
    attackPower: 54,
    speed: 80,
    criticalChance: 0.25,
    strongAgainst: 'artillery',
    weakAgainst: 'armor',
    trainingCost: { coins: 150, oil: 20, population: 2 },
    trainingTimeSeconds: 18,
    buildingSourceId: 'tent_barracks',
    icon: 'UserCheck',
    description: 'Elite amphibious infantry with high critical strike capabilities.',
  },
  {
    id: 'medium_tank',
    name: 'M4 Grizzly Tank',
    unitClass: 'armor',
    hp: 260,
    maxHp: 260,
    attackPower: 68,
    speed: 45,
    criticalChance: 0.2,
    strongAgainst: 'infantry',
    weakAgainst: 'artillery',
    trainingCost: { coins: 220, wood: 50, oil: 30, population: 3 },
    trainingTimeSeconds: 20,
    buildingSourceId: 'tank_factory',
    icon: 'Truck',
    description: 'Heavily armored war machine. Crushes enemy infantry with heavy cannon fire.',
  },
  {
    id: 'heavy_tank',
    name: 'Mammoth Heavy Tank',
    unitClass: 'armor',
    hp: 360,
    maxHp: 360,
    attackPower: 92,
    speed: 35,
    criticalChance: 0.22,
    strongAgainst: 'infantry',
    weakAgainst: 'artillery',
    trainingCost: { coins: 380, wood: 90, oil: 60, population: 4 },
    trainingTimeSeconds: 30,
    buildingSourceId: 'tank_factory',
    icon: 'Truck',
    description: 'Dual-cannon siege titan engineered to obliterate enemy ground divisions.',
  },
  {
    id: 'howitzer',
    name: 'Thunderbolt Howitzer',
    unitClass: 'artillery',
    hp: 130,
    maxHp: 130,
    attackPower: 95,
    speed: 30,
    criticalChance: 0.25,
    strongAgainst: 'armor',
    weakAgainst: 'infantry',
    trainingCost: { coins: 240, wood: 80, oil: 20, population: 2 },
    trainingTimeSeconds: 22,
    buildingSourceId: 'tent_barracks',
    icon: 'Crosshair',
    description: 'Long-range explosive ordnance. Devastates armored tanks from distance.',
  },
  {
    id: 'f18_raptor',
    name: 'F-18 Falcon Jet',
    unitClass: 'aircraft',
    hp: 180,
    maxHp: 180,
    attackPower: 85,
    speed: 90,
    criticalChance: 0.3,
    strongAgainst: 'naval',
    weakAgainst: 'artillery',
    trainingCost: { coins: 320, wood: 100, oil: 70, population: 3 },
    trainingTimeSeconds: 25,
    buildingSourceId: 'hangar_airfield',
    icon: 'Plane',
    description: 'Air superiority jet. Strikes gunboats and tactical installations with guided missiles.',
  },
  {
    id: 'stealth_bomber',
    name: 'B-2 Ghost Bomber',
    unitClass: 'aircraft',
    hp: 220,
    maxHp: 220,
    attackPower: 115,
    speed: 65,
    criticalChance: 0.35,
    strongAgainst: 'naval',
    weakAgainst: 'artillery',
    trainingCost: { coins: 500, wood: 140, oil: 110, population: 4 },
    trainingTimeSeconds: 35,
    buildingSourceId: 'hangar_airfield',
    icon: 'Plane',
    description: 'High-payload stealth bomber capable of leveling fortified enemy naval groups.',
  },
  {
    id: 'gunboat',
    name: 'Corsair Patrol Gunboat',
    unitClass: 'naval',
    hp: 310,
    maxHp: 310,
    attackPower: 72,
    speed: 40,
    criticalChance: 0.18,
    strongAgainst: 'armor',
    weakAgainst: 'aircraft',
    trainingCost: { coins: 280, wood: 110, oil: 40, population: 3 },
    trainingTimeSeconds: 24,
    buildingSourceId: 'naval_shipyard',
    icon: 'Anchor',
    description: 'Armored coastal patrol vessel providing artillery bombardments from the shore.',
  },
  {
    id: 'destroyer',
    name: 'Aegis Missile Destroyer',
    unitClass: 'naval',
    hp: 400,
    maxHp: 400,
    attackPower: 100,
    speed: 35,
    criticalChance: 0.25,
    strongAgainst: 'armor',
    weakAgainst: 'aircraft',
    trainingCost: { coins: 550, wood: 180, oil: 100, population: 5 },
    trainingTimeSeconds: 40,
    buildingSourceId: 'naval_shipyard',
    icon: 'Anchor',
    description: 'Capital naval warship armed with radar guidance and anti-ship missile pods.',
  },
];
