import type { CityBuildingDefinition } from '../types';

export const CITY_BUILDINGS_CATALOG: CityBuildingDefinition[] = [
  // 1. Residential (Houses & Apartments)
  {
    id: 'cozy_cottage',
    name: 'Cozy Cottage',
    category: 'residential',
    description: 'Charming starter home for incoming town residents. Houses 15 citizens and generates rent.',
    width: 2,
    height: 2,
    costCoins: 120,
    requiredLevel: 1,
    constructionTimeSeconds: 4,
    populationYield: 15,
    rentPayout: {
      amount: 45,
      intervalSeconds: 30,
    },
    color: '#38bdf8',
    accentColor: '#0284c7',
    icon: 'Home',
  },
  {
    id: 'suburban_home',
    name: 'Suburban Home',
    category: 'residential',
    description: 'Comfortable family home with manicured lawn. Houses 40 citizens.',
    width: 2,
    height: 2,
    costCoins: 300,
    requiredLevel: 2,
    constructionTimeSeconds: 8,
    populationYield: 40,
    rentPayout: {
      amount: 110,
      intervalSeconds: 60,
    },
    color: '#60a5fa',
    accentColor: '#2563eb',
    icon: 'Home',
  },
  {
    id: 'brick_brownstone',
    name: 'Classic Brownstone',
    category: 'residential',
    description: 'Multi-family historic townhouse in high-density urban zones. Houses 85 citizens.',
    width: 2,
    height: 2,
    costCoins: 750,
    requiredLevel: 3,
    constructionTimeSeconds: 15,
    populationYield: 85,
    rentPayout: {
      amount: 260,
      intervalSeconds: 120,
    },
    color: '#f97316',
    accentColor: '#c2410c',
    icon: 'Building',
  },
  {
    id: 'metropolis_condo',
    name: 'High-Rise Luxury Condos',
    category: 'residential',
    description: 'Towering residential skyscraper overlooking downtown avenues. Houses 200 citizens.',
    width: 3,
    height: 3,
    costCoins: 1800,
    requiredLevel: 4,
    constructionTimeSeconds: 25,
    populationYield: 200,
    rentPayout: {
      amount: 700,
      intervalSeconds: 240,
    },
    color: '#818cf8',
    accentColor: '#4f46e5',
    icon: 'Building2',
  },

  // 2. Community Buildings (Expand Population Cap)
  {
    id: 'city_hall',
    name: 'City Hall',
    category: 'community',
    description: 'Civic headquarters of local municipal government. Expands City Population Cap by +100.',
    width: 3,
    height: 3,
    costCoins: 500,
    requiredLevel: 1,
    constructionTimeSeconds: 10,
    populationCapBonus: 100,
    color: '#fbbf24',
    accentColor: '#d97706',
    icon: 'Landmark',
  },
  {
    id: 'police_station',
    name: 'Metropolitan Police Dept',
    category: 'community',
    description: 'Patrol precinct maintaining public safety and order. Expands Population Cap by +150.',
    width: 2,
    height: 2,
    costCoins: 650,
    requiredLevel: 2,
    constructionTimeSeconds: 12,
    populationCapBonus: 150,
    color: '#3b82f6',
    accentColor: '#1d4ed8',
    icon: 'Shield',
  },
  {
    id: 'post_office',
    name: 'City Postal Center',
    category: 'community',
    description: 'Central mail depot connecting citizens with parcel delivery. Expands Population Cap by +120.',
    width: 2,
    height: 2,
    costCoins: 550,
    requiredLevel: 2,
    constructionTimeSeconds: 10,
    populationCapBonus: 120,
    color: '#06b6d4',
    accentColor: '#0891b2',
    icon: 'Mail',
  },
  {
    id: 'firehouse',
    name: 'Engine Co. Firehouse',
    category: 'community',
    description: 'Stationed fire engines and emergency response teams. Expands Population Cap by +200.',
    width: 2,
    height: 2,
    costCoins: 900,
    requiredLevel: 3,
    constructionTimeSeconds: 18,
    populationCapBonus: 200,
    color: '#ef4444',
    accentColor: '#b91c1c',
    icon: 'Flame',
  },

  // 3. Businesses (Consume Goods to sell to citizens for Coins)
  {
    id: 'corner_bakery',
    name: 'Sweet Crust Bakery',
    category: 'business',
    description: 'Fresh pastries and sourdough breads. Consumes 25 Goods to stock, generating 140 Coins.',
    width: 2,
    height: 2,
    costCoins: 200,
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    goodsCost: 25,
    revenueCoins: 140,
    businessDurationSeconds: 40,
    color: '#f59e0b',
    accentColor: '#b45309',
    icon: 'Store',
  },
  {
    id: 'downtown_cafe',
    name: 'Java Perk Cafe',
    category: 'business',
    description: 'Artisanal espresso bar and bistro. Consumes 40 Goods to stock, generating 240 Coins.',
    width: 2,
    height: 2,
    costCoins: 380,
    requiredLevel: 2,
    constructionTimeSeconds: 10,
    goodsCost: 40,
    revenueCoins: 240,
    businessDurationSeconds: 60,
    color: '#a16207',
    accentColor: '#713f12',
    icon: 'Coffee',
  },
  {
    id: 'toy_emporium',
    name: 'Wonderland Toy Store',
    category: 'business',
    description: 'Board games, plushies, and robotic trains for kids. Consumes 60 Goods, yielding 380 Coins.',
    width: 2,
    height: 2,
    costCoins: 600,
    requiredLevel: 2,
    constructionTimeSeconds: 12,
    goodsCost: 60,
    revenueCoins: 380,
    businessDurationSeconds: 90,
    color: '#ec4899',
    accentColor: '#be185d',
    icon: 'Gift',
  },
  {
    id: 'movie_cinema',
    name: 'Starlight Cinema Palace',
    category: 'business',
    description: 'Downtown theater showing summer blockbusters. Consumes 100 Goods, yielding 720 Coins.',
    width: 3,
    height: 3,
    costCoins: 1200,
    requiredLevel: 3,
    constructionTimeSeconds: 20,
    goodsCost: 100,
    revenueCoins: 720,
    businessDurationSeconds: 180,
    color: '#8b5cf6',
    accentColor: '#6d28d9',
    icon: 'Film',
  },

  // 4. Farming Plot
  {
    id: 'farm_plot',
    name: 'Fertile Farm Plot',
    category: 'farming',
    description: 'Tillable plot of soil to plow and plant crops for your city Goods supply.',
    width: 2,
    height: 2,
    costCoins: 80,
    requiredLevel: 1,
    constructionTimeSeconds: 3,
    color: '#854d0e',
    accentColor: '#582e07',
    icon: 'Trees',
  },

  // 5. Roads
  {
    id: 'city_street',
    name: 'Paved Urban Avenue',
    category: 'road',
    description: 'Paved asphalt street with painted lane dividers and pedestrian sidewalks.',
    width: 1,
    height: 1,
    costCoins: 10,
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    color: '#334155',
    accentColor: '#1e293b',
    icon: 'Maximize2',
  },

  // 6. Decorations (Payout Multipliers)
  {
    id: 'fountain_plaza',
    name: 'Granite Water Fountain',
    category: 'decoration',
    description: 'Ornamental fountain attracting foot traffic. Boosts surrounding business payouts by +10%.',
    width: 2,
    height: 2,
    costCoins: 250,
    requiredLevel: 2,
    constructionTimeSeconds: 5,
    payoutBonusPercent: 10,
    color: '#06b6d4',
    accentColor: '#0891b2',
    icon: 'Sparkles',
  },
  {
    id: 'flower_park',
    name: 'Botanical Parklet',
    category: 'decoration',
    description: 'Flower beds, benches, and shade trees. Boosts nearby business payouts by +5%.',
    width: 1,
    height: 1,
    costCoins: 90,
    requiredLevel: 1,
    constructionTimeSeconds: 2,
    payoutBonusPercent: 5,
    color: '#22c55e',
    accentColor: '#15803d',
    icon: 'Trees',
  },
];
