import type { CityQuest } from '../types';

export const INITIAL_CITY_QUESTS: CityQuest[] = [
  {
    id: 'quest_first_home',
    title: 'Welcoming New Citizens',
    description: 'Every great city starts with a place to live! Build a Cozy Cottage to welcome our first citizens.',
    advisorName: 'Mayor Samantha',
    advisorAvatar: 'mayor_samantha',
    dialogue: [
      'Welcome, City Planner! I am Mayor Samantha. Our coastal valley is ready to bloom into a bustling metropolis.',
      'Start by opening the Build Menu and placing a Cozy Cottage for our first residents!',
    ],
    targetType: 'build',
    targetKey: 'cozy_cottage',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 150, xp: 50, energy: 3 },
  },
  {
    id: 'quest_farm_goods',
    title: 'Feed the Town',
    description: 'Businesses need goods to operate! Place a Farm Plot and plant Sweet Strawberries to produce your first shipment of Goods.',
    advisorName: 'Farmer Paul',
    advisorAvatar: 'farmer_paul',
    dialogue: [
      'Howdy! You cannot run businesses without Goods. Place a Farm Plot, click it to sow Strawberries, and harvest when ripe!',
    ],
    targetType: 'harvest_crop',
    targetKey: 'strawberries',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 200, goods: 40, xp: 80 },
  },
  {
    id: 'quest_open_bakery',
    title: 'Open for Business',
    description: 'Build a Sweet Crust Bakery along a road, then click it to stock it with your harvested Goods.',
    advisorName: 'Baker Pierre',
    advisorAvatar: 'baker_pierre',
    dialogue: [
      'Citizens are hungry for fresh bread! Build a Bakery, supply it with Goods, and watch the cash register ring!',
    ],
    targetType: 'restock',
    targetKey: 'corner_bakery',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 300, xp: 120 },
  },
  {
    id: 'quest_expand_cap',
    title: 'Civic Administration',
    description: 'Construct a City Hall to increase our maximum population capacity.',
    advisorName: 'Mayor Samantha',
    advisorAvatar: 'mayor_samantha',
    dialogue: [
      'Our city is growing rapidly! Community Buildings are required to raise our population cap. Construct City Hall!',
    ],
    targetType: 'build',
    targetKey: 'city_hall',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 500, xp: 200, energy: 5 },
  },
];
