import { BattleScenario, MapTheme, BaseAffiliation } from './types';

export const SCENARIOS: BattleScenario[] = [
  {
    id: 'yellow-turbans',
    chapter: 'Chapter 1',
    title: 'The Yellow Turban Rebellion',
    subtitle: 'Battle of Guangzong · 184 AD',
    description:
      'The mystic Zhang Jiao has rallied millions under the banner of the Yellow Sky. Rescue allied detachments, secure grain storehouses, and storm the Sorcerer’s Altar.',
    bossName: 'Zhang Jiao',
    bossTitle: 'General of Heaven · Yellow Turban High Priest',
    bossQuote: 'The Blue Sky has perished! The Yellow Sky shall reign supreme!',
    heroObjective: 'Capture the 3 rebel garrisons and defeat Zhang Jiao.',
    mapTheme: MapTheme.GRASSLAND,
    introDialogs: [
      {
        speaker: 'Liu Bei',
        title: 'Imperial Scion',
        avatarColor: '#3b82f6',
        text: 'Brothers! The realm bleeds under rebel sorcery. We must defend the innocent and restore the Han dynasty!',
        alignment: 'allied',
      },
      {
        speaker: 'Zhang Jiao',
        title: 'General of Heaven',
        avatarColor: '#eab308',
        text: 'Fools of the corrupt court! The heavens have granted me divine authority. Bow before the Yellow Turban gale!',
        alignment: 'enemy',
      },
    ],
    victoryDialogs: [
      {
        speaker: 'Guan Yu',
        title: 'God of War',
        avatarColor: '#16a34a',
        text: 'The rebel leader has fallen. Righteousness prevails once more across the plains of Guangzong.',
        alignment: 'allied',
      },
    ],
    objectives: [
      {
        id: 'obj_1',
        title: 'Clear Rebel Vanguard',
        description: 'Defeat 40 enemy rebels assaulting the forward perimeter.',
        type: 'kill_count',
        targetCount: 40,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture West Granary',
        description: 'Storm the West Supply Depot and defeat its gate captain.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Slay Zhang Jiao',
        description: 'Assault the Central Altar and defeat the High Priest.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Zhang Jiao',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Allied Main Encampment',
        x: 600,
        y: 600,
        radius: 200,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 800,
        maxDefenseHp: 800,
        bonusDesc: 'Headquarters: Spawns allied reinforcements',
      },
      {
        id: 'base_west',
        name: 'West Supply Granary',
        x: 700,
        y: 2200,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 500,
        maxDefenseHp: 500,
        bonusDesc: 'Capturing restores player HP and drops meat buns',
      },
      {
        id: 'base_east',
        name: 'East Lookout Watchtower',
        x: 2400,
        y: 800,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 500,
        maxDefenseHp: 500,
        bonusDesc: 'Capturing eliminates enemy sniper archers',
      },
      {
        id: 'base_citadel',
        name: 'Central Altar of Sorcery',
        x: 2800,
        y: 2800,
        radius: 260,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1000,
        maxDefenseHp: 1000,
        bonusDesc: 'Zhang Jiao’s inner sanctum',
      },
    ],
  },
  {
    id: 'hulao-gate',
    chapter: 'Chapter 2',
    title: 'The Tiger Cage of Hulao Gate',
    subtitle: 'Assault on Lu Bu · 190 AD',
    description:
      'The Eighteen Warlord Coalition arrives at the snowy ramparts of Hulao Gate. Dong Zhuo has unleashed the invincible God of War upon the snow-covered valley.',
    bossName: 'Lu Bu',
    bossTitle: 'The Flying General · Scourge of the Han',
    bossQuote: 'Can anyone here provide me a decent challenge?! Do not pursue Lu Bu!',
    heroObjective: 'Breach the outer fortifications and survive the duel with Lu Bu.',
    mapTheme: MapTheme.HULAO_SNOW,
    introDialogs: [
      {
        speaker: 'Cao Cao',
        title: 'Coalition Commander',
        avatarColor: '#3b82f6',
        text: 'Be on high alert! Hua Xiong has fallen, but the tyrant’s fiercest beast awaits beyond the gate.',
        alignment: 'allied',
      },
      {
        speaker: 'Lu Bu',
        title: 'The Flying General',
        avatarColor: '#dc2626',
        text: 'Insects! You dare march against my halberd? Come, face death upon the snows of Hulao!',
        alignment: 'enemy',
      },
    ],
    victoryDialogs: [
      {
        speaker: 'Zhao Yun',
        title: 'Dragon of Changban',
        avatarColor: '#38bdf8',
        text: 'The Flying General retreats! The gates of Luoyang lie open before the coalition!',
        alignment: 'allied',
      },
    ],
    objectives: [
      {
        id: 'obj_1',
        title: 'Breach Gate Barricades',
        description: 'Destroy 50 Dong Zhuo heavy infantry guards.',
        type: 'kill_count',
        targetCount: 50,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture East Ballista Bastion',
        description: 'Neutralize the siege catapult base raining heavy bolts.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_east',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Defeat Lu Bu',
        description: 'Duel the invincible God of War in the central plaza.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Lu Bu',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Coalition Vanguard Camp',
        x: 600,
        y: 600,
        radius: 200,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 800,
        maxDefenseHp: 800,
        bonusDesc: 'Coalition Command Base',
      },
      {
        id: 'base_west',
        name: 'West Fortified Rampart',
        x: 800,
        y: 2400,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 650,
        maxDefenseHp: 650,
        bonusDesc: 'Capturing halts enemy cavalry charges',
      },
      {
        id: 'base_east',
        name: 'East Ballista Bastion',
        x: 2500,
        y: 800,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 650,
        maxDefenseHp: 650,
        bonusDesc: 'Capturing gives allied artillery support',
      },
      {
        id: 'base_citadel',
        name: 'Hulao Main Gate Fort',
        x: 3000,
        y: 3000,
        radius: 280,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1200,
        maxDefenseHp: 1200,
        bonusDesc: 'Lu Bu’s stronghold',
      },
    ],
  },
  {
    id: 'chi-bi',
    chapter: 'Chapter 3',
    title: 'The Battle of Chi Bi',
    subtitle: 'Inferno at Red Cliffs · 208 AD',
    description:
      'The southern skies glow red over the Yangtze River. Zhuge Liang has summoned the southeast wind. Break through Cao Cao’s iron fleet and ignite the chained ships.',
    bossName: 'Zhang Liao',
    bossTitle: 'Vanguard Marshal of Wei',
    bossQuote: 'My blade never falters, even amidst a sea of flames!',
    heroObjective: 'Protect the wind altar, burn the supply fleet, and slay Zhang Liao.',
    mapTheme: MapTheme.CHIBI_FIRE,
    introDialogs: [
      {
        speaker: 'Zhou Yu',
        title: 'Viceroy of Wu',
        avatarColor: '#f97316',
        text: 'The wind has shifted! Ready the fire ships! Tonight, Cao Cao’s armada burns to ashes!',
        alignment: 'allied',
      },
      {
        speaker: 'Zhang Liao',
        title: 'Marshal of Wei',
        avatarColor: '#dc2626',
        text: 'Hold the lines! Do not let the southern rebels breach our anchored fleet!',
        alignment: 'enemy',
      },
    ],
    victoryDialogs: [
      {
        speaker: 'Lu Xun',
        title: 'Strategist of Wu',
        avatarColor: '#f97316',
        text: 'The flames consume the northern armada. The balance of the Three Kingdoms is struck!',
        alignment: 'allied',
      },
    ],
    objectives: [
      {
        id: 'obj_1',
        title: 'Repel Wei Boarding Parties',
        description: 'Cut down 60 enemy marines attempting to extinguish fire ships.',
        type: 'kill_count',
        targetCount: 60,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Ignite River Arsenal',
        description: 'Capture the Wei Gunpowder Depot in the eastern fleet.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_east',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Defeat Zhang Liao',
        description: 'Overcome Wei’s fiercest marshal at the flagship bridge.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Zhang Liao',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Wu Wind Altar Base',
        x: 600,
        y: 600,
        radius: 200,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 800,
        maxDefenseHp: 800,
        bonusDesc: 'Zhuge Liang’s prayer platform',
      },
      {
        id: 'base_west',
        name: 'Chained Ship West Wing',
        x: 800,
        y: 2500,
        radius: 230,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 700,
        maxDefenseHp: 700,
        bonusDesc: 'Wei navy boarding staging zone',
      },
      {
        id: 'base_east',
        name: 'Eastern Gunpowder Depot',
        x: 2600,
        y: 750,
        radius: 230,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 700,
        maxDefenseHp: 700,
        bonusDesc: 'Triggers chain reaction fire explosions',
      },
      {
        id: 'base_citadel',
        name: 'Cao Cao Imperial Flagship',
        x: 3100,
        y: 3100,
        radius: 290,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1300,
        maxDefenseHp: 1300,
        bonusDesc: 'Zhang Liao’s defensive command deck',
      },
    ],
  },
  {
    id: 'huarong-trail',
    chapter: 'Chapter 4',
    title: 'Escape Through Huarong Trail',
    subtitle: 'The Muddy Ambush Ravine · 208 AD',
    description:
      'Following the catastrophic inferno at Chi Bi, Cao Cao flees through the narrow, treacherous pass of Huarong. Intercept the elite Tiger and Leopard cavalry before they escape.',
    bossName: 'Cao Ren',
    bossTitle: 'The Iron Shield of Wei',
    bossQuote: 'My lord shall pass, even if I must drown this ravine in blood!',
    heroObjective: 'Secure the mountain pass and defeat Cao Ren’s rearguard.',
    mapTheme: MapTheme.RAVINE,
    introDialogs: [
      {
        speaker: 'Guan Yu',
        title: 'God of War',
        avatarColor: '#16a34a',
        text: 'Cao Cao, your treacherous path ends in this gorge. Face imperial justice!',
        alignment: 'allied',
      },
      {
        speaker: 'Cao Ren',
        title: 'The Iron Shield',
        avatarColor: '#dc2626',
        text: 'Lord Guan Yu! You will not harm our Lord while breath remains in my chest!',
        alignment: 'enemy',
      },
    ],
    victoryDialogs: [
      {
        speaker: 'Guan Yu',
        title: 'God of War',
        avatarColor: '#16a34a',
        text: 'Duty has been fulfilled. The Han dynasty will endure.',
        alignment: 'allied',
      },
    ],
    objectives: [
      {
        id: 'obj_1',
        title: 'Slay Iron Cavalry Retinue',
        description: 'Defeat 50 elite Tiger and Leopard cavalry.',
        type: 'kill_count',
        targetCount: 50,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Lock the Narrow Pass',
        description: 'Capture the Gorge Choke Point outpost.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Defeat Cao Ren',
        description: 'Overcome Wei’s indestructible defensive fortress general.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Cao Ren',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Guan Yu Ambush Camp',
        x: 600,
        y: 600,
        radius: 200,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 800,
        maxDefenseHp: 800,
        bonusDesc: 'Ambush start staging point',
      },
      {
        id: 'base_west',
        name: 'Narrow Gorge Choke Point',
        x: 900,
        y: 2300,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 750,
        maxDefenseHp: 750,
        bonusDesc: 'Cuts off enemy cavalry retreat',
      },
      {
        id: 'base_east',
        name: 'Cliffside Catapult Ridge',
        x: 2500,
        y: 800,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 700,
        maxDefenseHp: 700,
        bonusDesc: 'High ground bombardment battery',
      },
      {
        id: 'base_citadel',
        name: 'Cao Ren Rearguard Fort',
        x: 3000,
        y: 3000,
        radius: 280,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1400,
        maxDefenseHp: 1400,
        bonusDesc: 'The Iron Shield last stand',
      },
    ],
  },
];
