import { BattleScenario, MapTheme, BaseAffiliation } from './types';
import {
  YELLOW_TURBANS_INTRO,
  YELLOW_TURBANS_VICTORY,
  HULAO_GATE_INTRO,
  HULAO_GATE_VICTORY,
  CHI_BI_INTRO,
  CHI_BI_VICTORY,
  HUARONG_TRAIL_INTRO,
  HUARONG_TRAIL_VICTORY,
} from './storyDialogues';

export const SCENARIOS: BattleScenario[] = [
  {
    id: 'yellow-turbans',
    chapter: 'Chapter 1',
    title: 'The Yellow Turban Rebellion',
    subtitle: 'Battle of Guangzong · 184 AD',
    description:
      'The mystic Zhang Jiao has rallied millions under the banner of the Yellow Sky. Rescue allied detachments, secure grain storehouses, and storm the Sorcerer’s Altar.',
    bossName: 'Zhang Jiao',
    bossTitle: 'General of Heaven · Yellow Turban High Priest',
    bossQuote: 'The Blue Sky has perished! The Yellow Sky shall reign supreme!',
    heroObjective: 'Capture the 3 rebel garrisons and defeat Zhang Jiao.',
    mapTheme: MapTheme.GRASSLAND,
    introDialogs: YELLOW_TURBANS_INTRO,
    victoryDialogs: YELLOW_TURBANS_VICTORY,
    objectives: [
      {
        id: 'obj_1',
        title: 'Clear Rebel Vanguard',
        description: 'Defeat 75 enemy rebels assaulting the forward perimeter.',
        type: 'kill_count',
        targetCount: 75,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture West Granary',
        description: 'Storm the West Supply Depot and defeat its gate captain.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Slay Zhang Jiao',
        description: 'Assault the Central Altar and defeat the High Priest.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Zhang Jiao',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Allied Main Encampment',
        x: 600,
        y: 600,
        radius: 200,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 1200,
        maxDefenseHp: 1200,
        bonusDesc: 'Headquarters: Spawns allied reinforcements',
      },
      {
        id: 'base_west',
        name: 'West Supply Granary',
        x: 700,
        y: 2200,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1100,
        maxDefenseHp: 1100,
        bonusDesc: 'Capturing restores player HP and drops meat buns',
      },
      {
        id: 'base_east',
        name: 'East Lookout Watchtower',
        x: 2400,
        y: 800,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1200,
        maxDefenseHp: 1200,
        bonusDesc: 'Capturing disables enemy archer volleys',
      },
      {
        id: 'base_citadel',
        name: 'Zhang Jiao’s Sorcerer Altar',
        x: 2800,
        y: 2800,
        radius: 260,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1800,
        maxDefenseHp: 1800,
        bonusDesc: 'Final Stronghold: Spawns Supreme Boss Zhang Jiao',
      },
    ],
  },
  {
    id: 'hulao-gate',
    chapter: 'Chapter 2',
    title: 'The Tiger Cage of Hulao Gate',
    subtitle: 'Hulao Pass · 190 AD',
    description:
      'Eighteen lords unite under Yuan Shao to topple tyrant Dong Zhuo. But guarding the pass stands the demonic warlord Lu Bu atop the legendary steed Red Hare.',
    bossName: 'Lu Bu',
    bossTitle: 'The Mightiest Warrior · God of War',
    bossQuote: 'Can anybody provide me with a decent challenge?!',
    heroObjective: 'Breach the Catapult Bastion and survive against Lu Bu.',
    mapTheme: MapTheme.HULAO_SNOW,
    introDialogs: HULAO_GATE_INTRO,
    victoryDialogs: HULAO_GATE_VICTORY,
    objectives: [
      {
        id: 'obj_1',
        title: 'Break Dong Zhuo Vanguards',
        description: 'Slay 85 dread soldiers defending the snowy outer trenches.',
        type: 'kill_count',
        targetCount: 85,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture Catapult Bastion',
        description: 'Overrun the artillery terrace bombarding the coalition.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Duel and Repel Lu Bu',
        description: 'Face the invincible warlord at the inner fortress gates.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Lu Bu',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Coalition Forward Pavilion',
        x: 600,
        y: 600,
        radius: 220,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 1400,
        maxDefenseHp: 1400,
        bonusDesc: 'Coalition Vanguard Command',
      },
      {
        id: 'base_west',
        name: 'Catapult Artillery Bastion',
        x: 900,
        y: 2100,
        radius: 230,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1350,
        maxDefenseHp: 1350,
        bonusDesc: 'Halts siege boulder barrages',
      },
      {
        id: 'base_east',
        name: 'Iron Gate Outpost',
        x: 2200,
        y: 900,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1300,
        maxDefenseHp: 1300,
        bonusDesc: 'Reinforces allied morale upon capture',
      },
      {
        id: 'base_citadel',
        name: 'Hulao Gate Iron Fortress',
        x: 2900,
        y: 2900,
        radius: 280,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 2200,
        maxDefenseHp: 2200,
        bonusDesc: 'Dong Zhuo & Lu Bu Central Garrison',
      },
    ],
  },
  {
    id: 'chi-bi',
    chapter: 'Chapter 3',
    title: 'The Battle of Chi Bi',
    subtitle: 'Yangtze River · 208 AD',
    description:
      'Sun-Liu coalition forces ignite the northern armada! Battle through the blazing ship docks and repel General Zhang Liao’s elite division.',
    bossName: 'Zhang Liao',
    bossTitle: 'Wei Dragon Marshall · Hero of Hefei',
    bossQuote: 'My halberd shall carve a path through this sea of fire!',
    heroObjective: 'Ignite the supply docks and defeat Zhang Liao.',
    mapTheme: MapTheme.CHIBI_FIRE,
    introDialogs: CHI_BI_INTRO,
    victoryDialogs: CHI_BI_VICTORY,
    objectives: [
      {
        id: 'obj_1',
        title: 'Break Riverfront Defense',
        description: 'Neutralize 95 Wei marine vanguards.',
        type: 'kill_count',
        targetCount: 95,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture Gunpowder Depot',
        description: 'Secure the munitions warehouse and fuel the fire attack.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Defeat Zhang Liao',
        description: 'Duel the fearsome champion of Wei upon the flagship.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Zhang Liao',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Wu Flotilla Bridgehead',
        x: 600,
        y: 600,
        radius: 220,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 1350,
        maxDefenseHp: 1350,
        bonusDesc: 'Allied Naval Command',
      },
      {
        id: 'base_west',
        name: 'Chained Battleship Arsenal',
        x: 800,
        y: 2300,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1400,
        maxDefenseHp: 1400,
        bonusDesc: 'Ignites secondary explosions across enemy lines',
      },
      {
        id: 'base_east',
        name: 'Riverbank Signal Beacon',
        x: 2300,
        y: 800,
        radius: 200,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1300,
        maxDefenseHp: 1300,
        bonusDesc: 'Reveals enemy flankers on the minimap',
      },
      {
        id: 'base_citadel',
        name: 'Cao Cao’s Great Flagship',
        x: 2800,
        y: 2800,
        radius: 280,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 2400,
        maxDefenseHp: 2400,
        bonusDesc: 'Wei Central Fleet Headquarters',
      },
    ],
  },
  {
    id: 'huarong-trail',
    chapter: 'Chapter 4',
    title: 'Escape Through Huarong Trail',
    subtitle: 'Narrow Ravine · 208 AD',
    description:
      'Following the catastrophe at Chi Bi, Cao Cao flees through a muddy gorge. Intercept the retreating columns and confront Cao Ren’s rearguard.',
    bossName: 'Cao Ren',
    bossTitle: 'The Iron Fortress · Wei Great General',
    bossQuote: 'None shall touch Lord Cao Cao while breath remains in my chest!',
    heroObjective: 'Cut off the retreat path and defeat General Cao Ren.',
    mapTheme: MapTheme.RAVINE,
    introDialogs: HUARONG_TRAIL_INTRO,
    victoryDialogs: HUARONG_TRAIL_VICTORY,
    objectives: [
      {
        id: 'obj_1',
        title: 'Ambush Wei Rearguard',
        description: 'Defeat 100 elite escorts attempting to clear the ravine.',
        type: 'kill_count',
        targetCount: 100,
        currentCount: 0,
        completed: false,
      },
      {
        id: 'obj_2',
        title: 'Capture Ravine Bottleneck',
        description: 'Block the narrow pass to seal the escape route.',
        type: 'capture_base',
        targetCount: 1,
        currentCount: 0,
        targetId: 'base_west',
        completed: false,
      },
      {
        id: 'obj_3',
        title: 'Vanquish Cao Ren',
        description: 'Defeat the stalwart defender of Wei in personal combat.',
        type: 'boss',
        targetCount: 1,
        currentCount: 0,
        targetId: 'Cao Ren',
        completed: false,
      },
    ],
    bases: [
      {
        id: 'base_allied',
        name: 'Shu Ravine Ambush Camp',
        x: 600,
        y: 600,
        radius: 220,
        affiliation: BaseAffiliation.ALLIED,
        captureProgress: 100,
        defenseHp: 1400,
        maxDefenseHp: 1400,
        bonusDesc: 'Highland Overlook',
      },
      {
        id: 'base_west',
        name: 'Muddy Pass Barricade',
        x: 800,
        y: 2200,
        radius: 220,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1500,
        maxDefenseHp: 1500,
        bonusDesc: 'Seals escape corridor for bonus morale',
      },
      {
        id: 'base_east',
        name: 'Gorge Cavalry Watch',
        x: 2300,
        y: 800,
        radius: 210,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 1400,
        maxDefenseHp: 1400,
        bonusDesc: 'Slows down enemy cavalry charge speed',
      },
      {
        id: 'base_citadel',
        name: 'Cao Ren’s Stand Pavilion',
        x: 2850,
        y: 2850,
        radius: 270,
        affiliation: BaseAffiliation.ENEMY,
        captureProgress: 0,
        defenseHp: 2600,
        maxDefenseHp: 2600,
        bonusDesc: 'Defensive Bastion of the North',
      },
    ],
  },
];
