import type {
  BuildingDefinition,
  LauncherGame,
  Quest,
  UnitDefinition,
  CampaignSector,
  Superweapon,
  AllyCommander,
} from '../types';

export const INITIAL_BUILDINGS_CATALOG: BuildingDefinition[] = [
  {
    id: 'headquarters',
    name: 'Headquarters',
    description: 'Central Command Center of your military base. Unlocks high-tier facilities and houses war staff.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 0, wood: 0, oil: 0 },
    requiredLevel: 1,
    constructionTimeSeconds: 5,
    populationBonus: 40,
    color: '#3b82f6',
    accentColor: '#1d4ed8',
    icon: 'ShieldAlert',
  },
  {
    id: 'town_hall',
    name: 'Military Town Hall',
    description: 'Administers base operations and civic infrastructure. Raises maximum population capacity by +50.',
    category: 'community',
    width: 3,
    height: 3,
    cost: { coins: 500, wood: 200 },
    requiredLevel: 2,
    constructionTimeSeconds: 15,
    populationBonus: 50,
    color: '#8b5cf6',
    accentColor: '#6d28d9',
    icon: 'Building2',
  },
  {
    id: 'commander_cottage',
    name: 'Officer Cottage',
    description: 'Comfortable housing for military personnel and logistics crew. Generates 60 coins and houses 15 recruits.',
    category: 'residential',
    width: 2,
    height: 2,
    cost: { coins: 140, wood: 60 },
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    production: {
      resource: 'coins',
      amount: 60,
      intervalSeconds: 45,
    },
    populationCapacity: 15,
    color: '#ea580c',
    accentColor: '#9a3412',
    icon: 'Home',
  },
  {
    id: 'officer_villa',
    name: 'Staff Quarters',
    description: 'High-density military garrison. Yields 120 coins and houses 30 recruits.',
    category: 'residential',
    width: 2,
    height: 2,
    cost: { coins: 320, wood: 140 },
    requiredLevel: 2,
    constructionTimeSeconds: 12,
    production: {
      resource: 'coins',
      amount: 120,
      intervalSeconds: 60,
    },
    populationCapacity: 30,
    color: '#c2410c',
    accentColor: '#7c2d12',
    icon: 'Home',
  },
  {
    id: 'tent_barracks',
    name: 'Military Barracks',
    description: 'Trains infantry riflemen, scouts, and special forces commandos.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 150, wood: 60 },
    requiredLevel: 1,
    constructionTimeSeconds: 8,
    defenseScore: 15,
    color: '#10b981',
    accentColor: '#047857',
    icon: 'Tent',
  },
  {
    id: 'tank_factory',
    name: 'Armor Foundry',
    description: 'Manufactures Grizzly medium tanks and heavy armored fighting vehicles.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 350, wood: 120, oil: 50 },
    requiredLevel: 2,
    constructionTimeSeconds: 15,
    defenseScore: 30,
    color: '#f59e0b',
    accentColor: '#b45309',
    icon: 'Trophy',
  },
  {
    id: 'hangar_airfield',
    name: 'Airfield Hangar',
    description: 'Houses supersonic strike jets and high-altitude stealth bombers.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 600, wood: 250, oil: 120 },
    requiredLevel: 3,
    constructionTimeSeconds: 25,
    defenseScore: 45,
    color: '#6366f1',
    accentColor: '#4338ca',
    icon: 'Plane',
  },
  {
    id: 'naval_shipyard',
    name: 'Naval Port & Drydock',
    description: 'Constructed on shoreline edges. Builds patrol gunboats, destroyers, and submarines.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 550, wood: 220, oil: 90 },
    requiredLevel: 2,
    constructionTimeSeconds: 20,
    defenseScore: 40,
    isCoastal: true,
    color: '#0284c7',
    accentColor: '#0369a1',
    icon: 'Anchor',
  },
  {
    id: 'lumber_mill',
    name: 'Lumber Mill',
    description: 'Harvests timber from surrounding forests. Produces 40 wood per cycle.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 100 },
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    production: {
      resource: 'wood',
      amount: 40,
      intervalSeconds: 30,
    },
    color: '#84cc16',
    accentColor: '#4d7c0f',
    icon: 'Trees',
  },
  {
    id: 'gold_mine',
    name: 'Gold Treasury',
    description: 'Extracts precious ore and mints gold coins. Produces 80 coins per cycle.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 120, wood: 50 },
    requiredLevel: 1,
    constructionTimeSeconds: 10,
    production: {
      resource: 'coins',
      amount: 80,
      intervalSeconds: 40,
    },
    color: '#eab308',
    accentColor: '#a16207',
    icon: 'Coins',
  },
  {
    id: 'oil_refinery',
    name: 'Fuel Refinery',
    description: 'Refines crude oil into high-octane fuel for heavy armor and aviation.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 250, wood: 100 },
    requiredLevel: 2,
    constructionTimeSeconds: 18,
    production: {
      resource: 'oil',
      amount: 30,
      intervalSeconds: 45,
    },
    color: '#06b6d4',
    accentColor: '#0e7490',
    icon: 'Fuel',
  },
  {
    id: 'guard_tower',
    name: 'Patriot Defense Tower',
    description: 'Automated defense emplacement equipped with radar and surface-to-air missiles.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 180, wood: 75 },
    requiredLevel: 1,
    constructionTimeSeconds: 5,
    defenseScore: 25,
    color: '#ef4444',
    accentColor: '#b91c1c',
    icon: 'Crosshair',
  },
  {
    id: 'asphalt_road',
    name: 'Paved Supply Road',
    description: 'Connects military structures and facilitates supply logistics.',
    category: 'infrastructure',
    width: 1,
    height: 1,
    cost: { coins: 15 },
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    color: '#64748b',
    accentColor: '#334155',
    icon: 'Footprints',
  },
  {
    id: 'sandbag_barrier',
    name: 'Fortified Sandbags',
    description: 'Perimeter reinforcement protecting base installations from enemy fire.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 25, wood: 10 },
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    defenseScore: 8,
    color: '#d97706',
    accentColor: '#92400e',
    icon: 'Shield',
  },
];

export const COMBAT_UNITS_CATALOG: UnitDefinition[] = [
  {
    id: 'rifleman',
    name: 'Vanguard Rifleman',
    unitClass: 'infantry',
    hp: 120,
    maxHp: 120,
    attackPower: 38,
    speed: 70,
    criticalChance: 0.15,
    strongAgainst: 'artillery',
    weakAgainst: 'armor',
    trainingCost: { coins: 80, population: 1 },
    trainingTimeSeconds: 10,
    buildingSourceId: 'tent_barracks',
    icon: 'UserCheck',
    description: 'Fast mobile troopers. Closes in quickly to neutralize artillery emplacements.',
  },
  {
    id: 'commando',
    name: 'Special Forces Commando',
    unitClass: 'infantry',
    hp: 165,
    maxHp: 165,
    attackPower: 54,
    speed: 80,
    criticalChance: 0.25,
    strongAgainst: 'artillery',
    weakAgainst: 'armor',
    trainingCost: { coins: 150, oil: 20, population: 2 },
    trainingTimeSeconds: 18,
    buildingSourceId: 'tent_barracks',
    icon: 'UserCheck',
    description: 'Elite amphibious infantry with high critical strike capabilities.',
  },
  {
    id: 'medium_tank',
    name: 'M4 Grizzly Tank',
    unitClass: 'armor',
    hp: 260,
    maxHp: 260,
    attackPower: 68,
    speed: 45,
    criticalChance: 0.2,
    strongAgainst: 'infantry',
    weakAgainst: 'artillery',
    trainingCost: { coins: 220, wood: 50, oil: 30, population: 3 },
    trainingTimeSeconds: 20,
    buildingSourceId: 'tank_factory',
    icon: 'Truck',
    description: 'Heavily armored war machine. Crushes enemy infantry with heavy cannon fire.',
  },
  {
    id: 'heavy_tank',
    name: 'Mammoth Heavy Tank',
    unitClass: 'armor',
    hp: 360,
    maxHp: 360,
    attackPower: 92,
    speed: 35,
    criticalChance: 0.22,
    strongAgainst: 'infantry',
    weakAgainst: 'artillery',
    trainingCost: { coins: 380, wood: 90, oil: 60, population: 4 },
    trainingTimeSeconds: 30,
    buildingSourceId: 'tank_factory',
    icon: 'Truck',
    description: 'Dual-cannon siege titan engineered to obliterate enemy ground divisions.',
  },
  {
    id: 'howitzer',
    name: 'Thunderbolt Howitzer',
    unitClass: 'artillery',
    hp: 130,
    maxHp: 130,
    attackPower: 95,
    speed: 30,
    criticalChance: 0.25,
    strongAgainst: 'armor',
    weakAgainst: 'infantry',
    trainingCost: { coins: 240, wood: 80, oil: 20, population: 2 },
    trainingTimeSeconds: 22,
    buildingSourceId: 'tent_barracks',
    icon: 'Crosshair',
    description: 'Long-range explosive ordnance. Devastates armored tanks from distance.',
  },
  {
    id: 'f18_raptor',
    name: 'F-18 Falcon Jet',
    unitClass: 'aircraft',
    hp: 180,
    maxHp: 180,
    attackPower: 85,
    speed: 90,
    criticalChance: 0.3,
    strongAgainst: 'naval',
    weakAgainst: 'artillery',
    trainingCost: { coins: 320, wood: 100, oil: 70, population: 3 },
    trainingTimeSeconds: 25,
    buildingSourceId: 'hangar_airfield',
    icon: 'Plane',
    description: 'Air superiority jet. Strikes gunboats and tactical installations with guided missiles.',
  },
  {
    id: 'stealth_bomber',
    name: 'B-2 Ghost Bomber',
    unitClass: 'aircraft',
    hp: 220,
    maxHp: 220,
    attackPower: 115,
    speed: 65,
    criticalChance: 0.35,
    strongAgainst: 'naval',
    weakAgainst: 'artillery',
    trainingCost: { coins: 500, wood: 140, oil: 110, population: 4 },
    trainingTimeSeconds: 35,
    buildingSourceId: 'hangar_airfield',
    icon: 'Plane',
    description: 'High-payload stealth bomber capable of leveling fortified enemy naval groups.',
  },
  {
    id: 'gunboat',
    name: 'Corsair Patrol Gunboat',
    unitClass: 'naval',
    hp: 310,
    maxHp: 310,
    attackPower: 72,
    speed: 40,
    criticalChance: 0.18,
    strongAgainst: 'armor',
    weakAgainst: 'aircraft',
    trainingCost: { coins: 280, wood: 110, oil: 40, population: 3 },
    trainingTimeSeconds: 24,
    buildingSourceId: 'naval_shipyard',
    icon: 'Anchor',
    description: 'Armored coastal patrol vessel providing artillery bombardments from the shore.',
  },
  {
    id: 'destroyer',
    name: 'Aegis Missile Destroyer',
    unitClass: 'naval',
    hp: 400,
    maxHp: 400,
    attackPower: 100,
    speed: 35,
    criticalChance: 0.25,
    strongAgainst: 'armor',
    weakAgainst: 'aircraft',
    trainingCost: { coins: 550, wood: 180, oil: 100, population: 5 },
    trainingTimeSeconds: 40,
    buildingSourceId: 'naval_shipyard',
    icon: 'Anchor',
    description: 'Capital naval warship armed with radar guidance and anti-ship missile pods.',
  },
];

export const SUPERWEAPONS: Superweapon[] = [
  {
    id: 'tactical_nuke',
    name: 'Tactical Warhead',
    description: 'Unleashes devastating thermal devastation dealing 120 damage to all enemy units.',
    damage: 120,
    cost: { aluminum: 3, microchips: 2, steel: 4 },
    icon: 'Radiation',
  },
  {
    id: 'orbital_laser',
    name: 'Orbital Ion Cannon',
    description: 'Satellite beam that instantly annihilates an enemy armored or naval flagship for 180 damage.',
    damage: 180,
    cost: { microchips: 4, copper: 5 },
    icon: 'Zap',
  },
  {
    id: 'napalm_strike',
    name: 'Napalm Carpet Bomb',
    description: 'Incinerates the battlefield, dealing 75 damage across all enemy positions.',
    damage: 75,
    cost: { rubber: 4, aluminum: 3 },
    icon: 'Flame',
  },
];

export const CAMPAIGN_SECTORS: CampaignSector[] = [
  {
    id: 'sector_1',
    name: 'Sector 1: Outer Atoll',
    subtitle: 'Raven Syndicate Recon Vanguard',
    enemyCommander: 'Raven Scout Captain',
    difficulty: 1,
    rewards: { coins: 500, oil: 60, xp: 220, rareMaterial: 'steel' },
    isUnlocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_2',
    name: 'Sector 2: Iron Shallows',
    subtitle: 'Amphibious Armor & Patrol Boats',
    enemyCommander: 'Commander Vane',
    difficulty: 2,
    rewards: { coins: 850, oil: 110, xp: 380, rareMaterial: 'aluminum' },
    isUnlocked: true,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_3',
    name: 'Sector 3: Razor Ridge',
    subtitle: 'Fortified Howitzer Batteries',
    enemyCommander: 'Colonel Briggs',
    difficulty: 3,
    rewards: { coins: 1200, oil: 160, xp: 550, rareMaterial: 'rubber' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_4',
    name: 'Sector 4: Black Sky Airfield',
    subtitle: 'Raven Interceptor Squadron',
    enemyCommander: 'Major Drake',
    difficulty: 4,
    rewards: { coins: 1800, oil: 240, xp: 750, rareMaterial: 'copper' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
  {
    id: 'sector_5',
    name: 'Sector 5: Fortress Castor',
    subtitle: 'General Castor Dreadnought Citadel (BOSS)',
    enemyCommander: 'General Castor (Supreme Raven Leader)',
    difficulty: 5,
    rewards: { coins: 3500, oil: 500, xp: 1500, rareMaterial: 'microchips' },
    isUnlocked: false,
    isCompleted: false,
    stars: 0,
  },
];

export const INITIAL_ALLIES: AllyCommander[] = [
  {
    id: 'ally_major_foley',
    name: 'Major Foley',
    title: 'Senior Island Advisor',
    avatar: 'major_foley',
    level: 4,
    reputation: 150,
    hasVisitedToday: false,
    buildings: [
      { id: 'foley_hq', buildingTypeId: 'headquarters', gridX: 10, gridY: 10, level: 2, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'foley_barracks', buildingTypeId: 'tent_barracks', gridX: 14, gridY: 10, level: 2, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'foley_cottage', buildingTypeId: 'commander_cottage', gridX: 7, gridY: 10, level: 1, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'foley_mine', buildingTypeId: 'gold_mine', gridX: 7, gridY: 13, level: 1, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
    ],
  },
  {
    id: 'ally_sophia',
    name: 'Captain Sophia',
    title: 'Naval Armada Specialist',
    avatar: 'captain_sophia',
    level: 6,
    reputation: 320,
    hasVisitedToday: false,
    buildings: [
      { id: 'sophia_hq', buildingTypeId: 'headquarters', gridX: 10, gridY: 10, level: 3, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'sophia_shipyard', buildingTypeId: 'naval_shipyard', gridX: 14, gridY: 10, level: 2, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'sophia_airfield', buildingTypeId: 'hangar_airfield', gridX: 6, gridY: 9, level: 2, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
    ],
  },
  {
    id: 'ally_ramirez',
    name: 'Lt. Ramirez',
    title: 'Frontline Logistics Officer',
    avatar: 'lt_ramirez',
    level: 3,
    reputation: 90,
    hasVisitedToday: false,
    buildings: [
      { id: 'ramirez_hq', buildingTypeId: 'headquarters', gridX: 10, gridY: 10, level: 1, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'ramirez_lumber', buildingTypeId: 'lumber_mill', gridX: 14, gridY: 10, level: 1, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
      { id: 'ramirez_refinery', buildingTypeId: 'oil_refinery', gridX: 10, gridY: 14, level: 1, placedAt: 0, constructedAt: 0, isCompleted: true, lastHarvestAt: 0 },
    ],
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_hq_barracks',
    title: 'Fortify the Perimeter',
    description: 'The Raven Syndicate has occupied neighboring islands. Construct a Military Barracks to mobilize troops.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Commander, welcome to your new island command station! Raven Syndicate forces are scouting our perimeter.',
      'Construct a Military Barracks immediately so we can recruit vanguard riflemen for defense.',
    ],
    targetType: 'build',
    targetKey: 'tent_barracks',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 250, wood: 100, xp: 120, energy: 5 },
  },
  {
    id: 'quest_clear_wilderness',
    title: 'Reclaim Island Ground',
    description: 'Clear a wild jungle tree or granite boulder to expand our buildable island territory and gather materials.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Our base expansion is blocked by overgrown jungle and debris.',
      'Click on any wild tree or boulder in the outskirts to clear it with 1 energy and reclaim the ground!',
    ],
    targetType: 'clear',
    targetKey: 'any',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 200, wood: 100, xp: 110 },
  },
  {
    id: 'quest_recruit_squad',
    title: 'Mobilize the Vanguard',
    description: 'Open your Barracks and recruit 2 Vanguard Riflemen to fortify your Army Reserve.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'A barracks without trained soldiers is just canvas in the wind!',
      'Click your barracks, open the recruitment depot, and train 2 riflemen into your army reserve.',
    ],
    targetType: 'train',
    targetKey: 'rifleman',
    targetCount: 2,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 300, oil: 40, xp: 150 },
  },
  {
    id: 'quest_visit_foley',
    title: 'Allied Reconnaissance',
    description: 'Visit Major Foley’s base from the Allies dock and assist his installations to earn Honor points.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'We are stronger together, Commander. Check the Allies dock at the bottom of your screen.',
      'Visit my forward island base and assist my operations to earn valuable Honor points!',
    ],
    targetType: 'visit',
    targetKey: 'ally_major_foley',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 350, honor: 40, xp: 180 },
  },
  {
    id: 'quest_first_blood',
    title: 'Repel the Raven Scout',
    description: 'Deploy your squad in Sector 1 of the Campaign Map and eliminate the Raven Syndicate recon vanguard.',
    advisorName: 'General Castor',
    advisorAvatar: 'general_castor',
    dialogue: [
      'Alert! A Raven patrol is probing our perimeter at Sector 1.',
      'Take command of our tactical squad, exploit unit weaknesses, and secure victory!',
    ],
    targetType: 'combat',
    targetKey: 'sector_1',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 500, oil: 80, xp: 250, energy: 10 },
  },
];

export const LAUNCHER_GAMES: LauncherGame[] = [
  {
    id: 'empires-and-allies',
    title: 'Empires & Allies',
    tagline: 'Retro Military Island RTS & Tactical Turn-Based Combat',
    genre: 'Isometric RTS / Strategy',
    status: 'playable',
    releaseYear: '2011 / 2026 Remaster',
    bannerImage: 'military-base',
    description:
      'Build your military island fortress, command infantry, tanks, and fighter jets, and battle the nefarious Raven Syndicate in iconic rock-paper-scissors turn-based combat.',
    features: [
      'Isometric Diamond Base Building & Wilderness Clearing',
      'Population, Housing & Unit Training Depot',
      'Interactive Campaign World Map (5 Sectors)',
      'Turn-Based Combat with Projectile Ballistics & Screen Shake',
      'Allies Dock: Visit Neighbor Islands & Earn Honor Points',
      'HQ War Room: Craft Tactical Nukes & Superweapons',
    ],
  },
  {
    id: 'cityville',
    title: 'CityVille Retro',
    tagline: 'The Ultimate Isometric Metropolis Builder & Franchise Tycoon',
    genre: 'City Simulator / Tycoon',
    status: 'in_development',
    releaseYear: '2010 Classic',
    bannerImage: 'city-skyline',
    description:
      'Pave downtown roads, construct townhomes, operate bakeries and toy shops, and run supply deliveries to grow your bustling island town into a thriving metropolis.',
    features: [
      'Franchise Stores & Goods Supply Deliveries',
      'Zoning: Residential, Commercial, and Public Landmarks',
      'Community Buildings & Population Caps',
      'Traffic Simulation & Citizen Happiness',
    ],
  },
  {
    id: 'farmville-retro',
    title: 'FarmVille Vintage',
    tagline: 'Plow, Plant, and Harvest Across Serene Pastoral Farmlands',
    genre: 'Farming Simulation',
    status: 'coming_soon',
    releaseYear: '2009 Classic',
    bannerImage: 'farm-landscape',
    description:
      'The legendary social farming experience. Plow plots, sow wheat, strawberries, and pumpkins, raise livestock, and harvest prize crops.',
    features: [
      'Tile Plowing & Crop Ripening Timers',
      'Barns, Tractors & Farm Animal Pens',
      'Marketplace Trading & Ribbon Achievements',
    ],
  },
];
