import type { BuildingDefinition, LauncherGame, Quest, UnitDefinition } from '../types';

export const INITIAL_BUILDINGS_CATALOG: BuildingDefinition[] = [
  {
    id: 'headquarters',
    name: 'Headquarters',
    description: 'Central Command Center of your military base. Unlocks high-tier facilities.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 0, wood: 0, oil: 0 },
    requiredLevel: 1,
    constructionTimeSeconds: 5,
    populationCapacity: 50,
    color: '#3b82f6',
    accentColor: '#1d4ed8',
    icon: 'ShieldAlert',
  },
  {
    id: 'tent_barracks',
    name: 'Military Barracks',
    description: 'Trains infantry riflemen and special forces for forward operations.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 150, wood: 60 },
    requiredLevel: 1,
    constructionTimeSeconds: 8,
    populationCapacity: 20,
    defenseScore: 15,
    color: '#10b981',
    accentColor: '#047857',
    icon: 'Tent',
  },
  {
    id: 'tank_factory',
    name: 'Armor Foundry',
    description: 'Manufactures heavy battle tanks and armored fighting vehicles.',
    category: 'military',
    width: 2,
    height: 2,
    cost: { coins: 350, wood: 120, oil: 50 },
    requiredLevel: 2,
    constructionTimeSeconds: 15,
    defenseScore: 30,
    color: '#f59e0b',
    accentColor: '#b45309',
    icon: 'Trophy',
  },
  {
    id: 'hangar_airfield',
    name: 'Airfield Hangar',
    description: 'Houses supersonic strike jets and aerial reconnaissance drones.',
    category: 'military',
    width: 3,
    height: 3,
    cost: { coins: 600, wood: 250, oil: 120 },
    requiredLevel: 3,
    constructionTimeSeconds: 25,
    defenseScore: 45,
    color: '#6366f1',
    accentColor: '#4338ca',
    icon: 'Plane',
  },
  {
    id: 'lumber_mill',
    name: 'Lumber Mill',
    description: 'Harvests timber from surrounding forests. Produces 40 wood per cycle.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 100 },
    requiredLevel: 1,
    constructionTimeSeconds: 6,
    production: {
      resource: 'wood',
      amount: 40,
      intervalSeconds: 30,
    },
    color: '#84cc16',
    accentColor: '#4d7c0f',
    icon: 'Trees',
  },
  {
    id: 'gold_mine',
    name: 'Gold Treasury',
    description: 'Extracts precious ore and mints gold coins. Produces 80 coins per cycle.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 120, wood: 50 },
    requiredLevel: 1,
    constructionTimeSeconds: 10,
    production: {
      resource: 'coins',
      amount: 80,
      intervalSeconds: 40,
    },
    color: '#eab308',
    accentColor: '#a16207',
    icon: 'Coins',
  },
  {
    id: 'oil_refinery',
    name: 'Fuel Refinery',
    description: 'Refines crude oil into high-octane fuel for heavy armor and aviation.',
    category: 'production',
    width: 2,
    height: 2,
    cost: { coins: 250, wood: 100 },
    requiredLevel: 2,
    constructionTimeSeconds: 18,
    production: {
      resource: 'oil',
      amount: 30,
      intervalSeconds: 45,
    },
    color: '#06b6d4',
    accentColor: '#0e7490',
    icon: 'Fuel',
  },
  {
    id: 'guard_tower',
    name: 'Patriot Defense Tower',
    description: 'Automated defense emplacement equipped with radar and surface missiles.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 180, wood: 75 },
    requiredLevel: 1,
    constructionTimeSeconds: 5,
    defenseScore: 25,
    color: '#ef4444',
    accentColor: '#b91c1c',
    icon: 'Crosshair',
  },
  {
    id: 'asphalt_road',
    name: 'Paved Supply Road',
    description: 'Connects military structures and speeds base logistics movement.',
    category: 'infrastructure',
    width: 1,
    height: 1,
    cost: { coins: 15 },
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    color: '#64748b',
    accentColor: '#334155',
    icon: 'Footprints',
  },
  {
    id: 'sandbag_barrier',
    name: 'Fortified Sandbags',
    description: 'Perimeter reinforcement protecting perimeter against light fire.',
    category: 'defense',
    width: 1,
    height: 1,
    cost: { coins: 25, wood: 10 },
    requiredLevel: 1,
    constructionTimeSeconds: 1,
    defenseScore: 8,
    color: '#d97706',
    accentColor: '#92400e',
    icon: 'Shield',
  },
];

export const COMBAT_UNITS_CATALOG: UnitDefinition[] = [
  {
    id: 'rifleman',
    name: 'Vanguard Rifleman',
    unitClass: 'infantry',
    hp: 120,
    maxHp: 120,
    attackPower: 38,
    speed: 70,
    criticalChance: 0.15,
    strongAgainst: 'artillery',
    weakAgainst: 'armor',
    icon: 'UserCheck',
    description: 'Mobile ground troopers. Closes in quickly to neutralize artillery emplacements.',
  },
  {
    id: 'medium_tank',
    name: 'M4 Grizzly Tank',
    unitClass: 'armor',
    hp: 260,
    maxHp: 260,
    attackPower: 68,
    speed: 45,
    criticalChance: 0.2,
    strongAgainst: 'infantry',
    weakAgainst: 'artillery',
    icon: 'Truck',
    description: 'Heavily armored war machine. Crushes enemy infantry with heavy cannon fire.',
  },
  {
    id: 'howitzer',
    name: 'Thunderbolt Howitzer',
    unitClass: 'artillery',
    hp: 130,
    maxHp: 130,
    attackPower: 95,
    speed: 30,
    criticalChance: 0.25,
    strongAgainst: 'armor',
    weakAgainst: 'infantry',
    icon: 'Crosshair',
    description: 'Long-range explosive ordnance. Devastates armored tanks from distance.',
  },
  {
    id: 'f18_raptor',
    name: 'F-18 Falcon Jet',
    unitClass: 'aircraft',
    hp: 180,
    maxHp: 180,
    attackPower: 85,
    speed: 90,
    criticalChance: 0.3,
    strongAgainst: 'naval',
    weakAgainst: 'artillery',
    icon: 'Plane',
    description: 'Air superiority jet. Strikes gunboats and tactical installations with guided missiles.',
  },
  {
    id: 'gunboat',
    name: 'Corsair Patrol Gunboat',
    unitClass: 'naval',
    hp: 310,
    maxHp: 310,
    attackPower: 72,
    speed: 40,
    criticalChance: 0.18,
    strongAgainst: 'armor',
    weakAgainst: 'aircraft',
    icon: 'Anchor',
    description: 'Armored coastal patrol vessel providing artillery bombardments from the shore.',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'quest_hq_barracks',
    title: 'Fortify the Perimeter',
    description: 'Our scout reports Raven Syndicate movement. Construct a Military Barracks to recruit forces.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Commander, glad to have you on the island! The Raven Syndicate has occupied neighboring islands.',
      'We need you to build a Military Barracks immediately so we can mobilize riflemen for defense.',
    ],
    targetType: 'build',
    targetKey: 'tent_barracks',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 250, wood: 100, xp: 120, energy: 5 },
  },
  {
    id: 'quest_wood_economy',
    title: 'Timber for War',
    description: 'Construct a Lumber Mill to secure a steady supply of wood for new fortifications.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'Good work on the barracks, Commander! Now our construction engineers need timber.',
      'Build a Lumber Mill and collect your first harvest when the lumber is ready.',
    ],
    targetType: 'build',
    targetKey: 'lumber_mill',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 200, wood: 80, xp: 100 },
  },
  {
    id: 'quest_first_blood',
    title: 'Repel the Raven Scout',
    description: 'Deploy your squad to Sector 1 and eliminate the Raven Syndicate recon vanguard.',
    advisorName: 'General Castor',
    advisorAvatar: 'general_castor',
    dialogue: [
      'Alert! A Raven patrol is probing our perimeter at Sector 1.',
      'Take command of our tactical squad, exploit their unit weaknesses, and secure victory!',
    ],
    targetType: 'combat',
    targetKey: 'sector_1',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 500, oil: 80, xp: 250, energy: 10 },
  },
  {
    id: 'quest_heavy_foundry',
    title: 'Armor Superiority',
    description: 'Construct an Armor Foundry to manufacture battle tanks.',
    advisorName: 'Major Foley',
    advisorAvatar: 'major_foley',
    dialogue: [
      'The enemy is fielding heavier weapons. Construct an Armor Foundry to deploy tanks against their infantry.',
    ],
    targetType: 'build',
    targetKey: 'tank_factory',
    targetCount: 1,
    currentCount: 0,
    isCompleted: false,
    rewards: { coins: 400, oil: 50, xp: 200 },
  },
];

export const LAUNCHER_GAMES: LauncherGame[] = [
  {
    id: 'empires-and-allies',
    title: 'Empires & Allies',
    tagline: 'Retro Military Island RTS & Tactical Turn-Based Combat',
    genre: 'Isometric RTS / Strategy',
    status: 'playable',
    releaseYear: '2011 / 2026 Remaster',
    bannerImage: 'military-base',
    description:
      'Build your military island fortress, command infantry, tanks, and fighter jets, and battle the nefarious Raven Syndicate in iconic rock-paper-scissors turn-based combat.',
    features: [
      'Isometric Diamond Base Building & Grid Placement',
      'Turn-Based 5v5 Tactical Combat Arena',
      'Resource Loop (Gold, Wood, Fuel, Energy)',
      'Story Campaign Quests with Major Foley & Raven Bosses',
      'Offline Idle Resource Accrual & Local Save Sync',
    ],
  },
  {
    id: 'cityville',
    title: 'CityVille Retro',
    tagline: 'The Ultimate Isometric Metropolis Builder & Franchise Tycoon',
    genre: 'City Simulator / Tycoon',
    status: 'in_development',
    releaseYear: '2010 Classic',
    bannerImage: 'city-skyline',
    description:
      'Pave downtown roads, construct townhomes, operate bakeries and toy shops, and run supply deliveries to grow your bustling island town into a thriving metropolis.',
    features: [
      'Franchise Stores & Goods Supply Deliveries',
      'Zoning: Residential, Commercial, and Public Landmarks',
      'Community Buildings & Population Caps',
      'Traffic Simulation & Citizen Happiness',
    ],
  },
  {
    id: 'farmville-retro',
    title: 'FarmVille Vintage',
    tagline: 'Plow, Plant, and Harvest Across Serene Pastoral Farmlands',
    genre: 'Farming Simulation',
    status: 'coming_soon',
    releaseYear: '2009 Classic',
    bannerImage: 'farm-landscape',
    description:
      'The legendary social farming experience. Plow plots, sow wheat, strawberries, and pumpkins, raise livestock, and harvest prize crops.',
    features: [
      'Tile Plowing & Crop Ripening Timers',
      'Barns, Tractors & Farm Animal Pens',
      'Marketplace Trading & Ribbon Achievements',
    ],
  },
];
