import type { LauncherGame } from '../types';

export const LAUNCHER_GAMES: LauncherGame[] = [
  {
    id: 'empires-and-allies',
    title: 'Empires & Allies',
    tagline: 'Retro Military Island RTS & Tactical Turn-Based Combat',
    genre: 'Isometric RTS / Military Strategy',
    category: 'strategy',
    status: 'playable',
    releaseYear: '2011 / 2026 Remaster',
    developer: 'Zynga Classic Remastered',
    rating: 4.9,
    playerCount: '39M+ Peak Players',
    storageSize: '12 MB Local Cache',
    accentColor: '#f59e0b',
    bannerImage: 'military-base',
    description:
      'Take command of your island archipelago fortress! Pave military supply roads, construct barracks and armor foundries, train armor and fighter wings, and wage tactical rock-paper-scissors warfare against the ruthless Raven Syndicate.',
    features: [
      'Isometric Diamond Base Building & Wilderness Clearing',
      'Population, Housing & Unit Training Depot',
      'Interactive Campaign World Map (5 Sectors)',
      'Turn-Based Combat with Projectile Ballistics & Screen Shake',
      'Allies Dock: Visit Neighbor Islands & Earn Honor Points',
      'HQ War Room: Craft Tactical Nukes & Superweapons',
    ],
  },
  {
    id: 'cityville',
    title: 'CityVille Retro',
    tagline: 'The Ultimate Isometric Metropolis Builder & Franchise Tycoon',
    genre: 'City Simulator / Economic Tycoon',
    category: 'tycoon',
    status: 'playable',
    releaseYear: '2010 Classic',
    developer: 'Zynga Classic Remastered',
    rating: 4.8,
    playerCount: '100M+ Monthly Users',
    storageSize: '8 MB Local Cache',
    accentColor: '#38bdf8',
    bannerImage: 'city-skyline',
    description:
      'Pave downtown avenues, zone townhomes, plow fertile crops, and stock bakeries and boutiques with harvested goods. Manage the classic Triangle Economy of Coins, Goods, and Population Cap to build a thriving metropolis.',
    features: [
      'The Triangle Economy: Coins, Goods Supply & Population Cap',
      'Farming Plots: Sow Strawberries, Carrots & Sweet Corn',
      'Retail Businesses: Restock Bakeries & Cafes for High Revenue',
      'Community Buildings: City Hall, Police Station & Firehouse',
      'Freight Port: Order Cargo Ships & Freight Rail Shipments',
      'Traffic Simulation: Yellow Taxis, Delivery Vans & Citizens',
    ],
  },
  {
    id: 'farmville-vintage',
    title: 'FarmVille Vintage',
    tagline: 'Plow, Plant, and Harvest Across Pastoral Farmlands',
    genre: 'Pastoral Agriculture Simulation',
    category: 'farming',
    status: 'in_development',
    releaseYear: '2009 Classic',
    developer: 'Zynga Original',
    rating: 4.7,
    playerCount: '83M+ Monthly Users',
    storageSize: '6 MB',
    accentColor: '#22c55e',
    bannerImage: 'farm-landscape',
    description:
      'The legendary social farming game that started it all. Till soil plots, plant prize wheat and berries, harvest before crops wither, build red barns, and care for dairy cows and horses.',
    features: [
      'Grid Plowing & Crop Ripening Growth Timers',
      'Barns, Tractors & Dairy Animal Enclosures',
      'Harvest Multipliers & Neighbor Crop Fertilization',
      'Vintage Ribbon & Trophy System',
    ],
  },
  {
    id: 'castleville-legends',
    title: 'CastleVille Legends',
    tagline: 'Medieval Kingdom Restoration & Gloom Forest Exploration',
    genre: 'Medieval Fantasy Kingdom Builder',
    category: 'strategy',
    status: 'coming_soon',
    releaseYear: '2011 Classic',
    developer: 'Zynga Dallas',
    rating: 4.6,
    playerCount: '25M+ Players',
    storageSize: '15 MB',
    accentColor: '#a855f7',
    bannerImage: 'castle-kingdom',
    description:
      'Lift the mysterious Gloom shrouding your enchanted kingdom! Construct stone keeps, craft arcane potions, forge knightly armor, and complete quests with Duke and Maiden allies.',
    features: [
      'Gloom Fog Exploration & Land Purification',
      'Workshop Crafting: Iron Ingots, Wood Planks & Magic Potions',
      'Stone Castles, Watchtowers & Royal Palaces',
    ],
  },
  {
    id: 'frontier-ville',
    title: 'FrontierVille & Pioneer Trail',
    tagline: 'Tame the Wild West Frontier with Grit and Tenacity',
    genre: 'Wild West Homestead Survival',
    category: 'simulation',
    status: 'coming_soon',
    releaseYear: '2010 Classic',
    developer: 'Zynga East',
    rating: 4.7,
    playerCount: '30M+ Players',
    storageSize: '10 MB',
    accentColor: '#ea580c',
    bannerImage: 'frontier-outpost',
    description:
      'Chop down wilderness oak trees, fend off bears and wild snakes, build log cabins, marry a pioneer partner, and raise a homestead family along the legendary frontier trail.',
    features: [
      'Wilderness Clearing: Timber Felling & Wild Boulders',
      'Cabin Construction, Schoolhouse & Blacksmith',
      'Wild West Varmint Encounters: Snakes & Groundhogs',
    ],
  },
  {
    id: 'mafia-wars',
    title: 'Mafia Wars Syndicate',
    tagline: 'Climb the Crime Underworld from Street Hustler to Capo',
    genre: 'Underground Strategy RPG',
    category: 'rpg',
    status: 'coming_soon',
    releaseYear: '2008 Classic',
    developer: 'Zynga Underground',
    rating: 4.5,
    playerCount: '45M+ Players',
    storageSize: '5 MB',
    accentColor: '#ef4444',
    bannerImage: 'mafia-syndicate',
    description:
      'Carry out mob jobs across New York, Cuba, and Moscow! Assemble your mafia family, equip high-caliber firearms, purchase laundering properties, and wage family cartel wars.',
    features: [
      'Job Progression: Street Thief, Enforcer, Hitman & Don',
      'Cartel Wars & Hitlist Bounties',
      'Laundering Real Estate: Casinos, Docks & Nightclubs',
    ],
  },
  {
    id: 'chefville-culinary',
    title: 'ChefVille Gourmet',
    tagline: 'Cook World-Class Recipes and Build a Michelin Restaurant',
    genre: 'Culinary Restaurant Tycoon',
    category: 'tycoon',
    status: 'coming_soon',
    releaseYear: '2012 Classic',
    developer: 'Zynga Dining',
    rating: 4.6,
    playerCount: '20M+ Players',
    storageSize: '8 MB',
    accentColor: '#f97316',
    bannerImage: 'restaurant-kitchen',
    description:
      'Source fresh farm ingredients, fire up brick pizza ovens, grill Kobe steaks, and serve hungry food critics in your dream bistro.',
    features: [
      'Authentic Masterchef Recipes & Ingredient Harvesting',
      'Commercial Kitchen Equipment: Woks, Grills & Brick Ovens',
      'Gourmet Rating & Critic Reviews',
    ],
  },
  {
    id: 'petville-sanctuary',
    title: 'PetVille Sanctuary',
    tagline: 'Adopt, Dress, and Design Cozy Homes for Beloved Pets',
    genre: 'Pet Simulation & Village',
    category: 'casual',
    status: 'coming_soon',
    releaseYear: '2009 Classic',
    developer: 'Zynga Care',
    rating: 4.4,
    playerCount: '18M+ Players',
    storageSize: '7 MB',
    accentColor: '#ec4899',
    bannerImage: 'pet-sanctuary',
    description:
      'Create personalized puppy and kitten companions! Bathe, feed, play dress-up with stylish outfits, and customize themed living rooms with plush furniture.',
    features: [
      'Custom Pet Care: Bathing, Feeding & Play sessions',
      'Interior Design: Furniture, Wallpaper & Rugs',
      'Pet Boutique Fashion & Treat Dispensary',
    ],
  },
  {
    id: 'treasure-isle',
    title: 'Treasure Isle',
    tagline: 'Excavate Ancient Ruins and Discover Priceless Relics',
    genre: 'Adventure / Archeology',
    category: 'strategy',
    status: 'coming_soon',
    releaseYear: '2010 Classic',
    developer: 'Zynga Adventure',
    rating: 4.5,
    playerCount: '29M+ Players',
    storageSize: '9 MB',
    accentColor: '#eab308',
    bannerImage: 'treasure-ruins',
    description:
      'Sail your explorer yacht across tropical archipelagos! Dig through volcanic caverns and temple tombs to unearth golden idols and assemble museum collections.',
    features: [
      'Grid Excavation: Digging for Hidden Artifacts',
      'Museum Relic Displays & Collection Rewards',
      'Island Hopping via Explorer Vessels',
    ],
  },
  {
    id: 'the-ville-social',
    title: 'The Ville Social',
    tagline: 'Life Simulation, House Parties, and Dream Mansions',
    genre: 'Social Life Simulation',
    category: 'casual',
    status: 'coming_soon',
    releaseYear: '2012 Classic',
    developer: 'Zynga Living',
    rating: 4.3,
    playerCount: '15M+ Players',
    storageSize: '11 MB',
    accentColor: '#06b6d4',
    bannerImage: 'social-mansion',
    description:
      'Design dream contemporary villas, socialize with neighbors, throw pool parties, dance to jukebox tracks, and level up career aspirations.',
    features: [
      'Architectural House Construction & Floor Plan Design',
      'Social Emotes, Pool Parties & Barbecue Gatherings',
      'Career Aspirations & Skill Training',
    ],
  },
  {
    id: 'coasterville-park',
    title: 'CoasterVille Amusement',
    tagline: 'Engineer Thrilling Roller Coasters & Festive Carnivals',
    genre: 'Theme Park Tycoon',
    category: 'tycoon',
    status: 'coming_soon',
    releaseYear: '2012 Classic',
    developer: 'Zynga Parks',
    rating: 4.6,
    playerCount: '22M+ Players',
    storageSize: '14 MB',
    accentColor: '#8b5cf6',
    bannerImage: 'theme-park',
    description:
      'Lay down high-speed coaster track loops, install Ferris wheels and bumper cars, build cotton candy stalls, and keep park guests cheering with thrill-ride upgrades.',
    features: [
      'Modular Coaster Track Engineering: Drops & Inversions',
      'Carnival Attractions, Arcade Games & Food Stalls',
      'Thrill Meter & Park Guest Satisfaction',
    ],
  },
  {
    id: 'fishville-aquarium',
    title: 'FishVille Deep Blue',
    tagline: 'Cultivate Exotic Corals and Breed Luminous Tropical Fish',
    genre: 'Aquatic Simulation',
    category: 'casual',
    status: 'coming_soon',
    releaseYear: '2009 Classic',
    developer: 'Zynga Ocean',
    rating: 4.4,
    playerCount: '14M+ Players',
    storageSize: '6 MB',
    accentColor: '#0284c7',
    bannerImage: 'deep-aquarium',
    description:
      'Nurture rare clownfish, angelfish, and seahorses in custom glass aquariums! Plant glowing anemones, feed your school of fish, and keep tanks sparkling clean.',
    features: [
      'Aquarium Tank Cleaning & Feeding Schedule',
      'Exotic Fish Breeding & Rare Color Variants',
      'Living Coral Reefs, Shipwrecks & Sunken Statues',
    ],
  },
];
