import type { LauncherGame } from '../types';

export const LAUNCHER_GAMES: LauncherGame[] = [
  {
    id: 'empires-and-allies',
    title: 'Empires & Allies',
    tagline: 'Military island base builder with turn-based tactical combat',
    genre: 'Isometric RTS',
    category: 'strategy',
    status: 'playable',
    releaseYear: '2011',
    accentColor: '#f59e0b',
    description:
      'Build your island fortress, train infantry, tanks, and fighter jets, then battle the Raven Syndicate in turn-based tactical combat.',
    features: [
      'Isometric base building on a diamond grid',
      'Wilderness clearing and resource harvesting',
      'Turn-based tactical combat with screen shake',
      'Five-sector campaign world map',
      'Neighbor island visiting and honor points',
      'War Room superweapon crafting',
    ],
  },
  {
    id: 'cityville',
    title: 'CityVille',
    tagline: 'City builder with farming, retail restocking, and population management',
    genre: 'City Sim / Tycoon',
    category: 'tycoon',
    status: 'playable',
    releaseYear: '2010',
    accentColor: '#38bdf8',
    description:
      'Zone residential and commercial lots, plow crops, stock bakeries with harvested goods, and balance the triangle economy of Coins, Goods, and Population.',
    features: [
      'Triangle economy: Coins, Goods, and Population cap',
      'Farming plots with crop growth timers',
      'Retail businesses that consume goods for revenue',
      'Community buildings that raise population cap',
      'Freight port with cargo ship contracts',
      'Traffic simulation with taxis, vans, and pedestrians',
    ],
  },
  {
    id: 'dynasty-legends',
    title: 'Dynasty Legends: AI Warlords',
    tagline: 'Three Kingdoms hack-and-slash action battle with officer duels and Musou attacks',
    genre: 'Musou Action',
    category: 'action',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#ef4444',
    description:
      'Choose your legendary hero (Guan Yu, Zhao Yun, Lu Bu, Lu Xun), cut through enemy soldier ranks, duel enemy officers, and unleash room-clearing Musou ultimate abilities across historical battlefield scenarios.',
    features: [
      'Four playable heroes with distinct attack styles and stats',
      'Multiple battlefield scenarios: Yellow Turban, Hu Lao Gate, Chi Bi',
      'Musou meter system with screen-clearing rage attacks',
      'Minimap tactical view tracking enemy clusters and officers',
      'Item drops: Meat buns (HP), Wine (Musou), Axes, Armor',
      'Difficulty tiers: Normal, Hard, Chaos',
    ],
  },
  {
    id: 'rubik-cube',
    title: "Rubik's Cube 3D",
    tagline: 'Interactive 3D puzzle cube with layer rotations, scramble, and move tracking',
    genre: '3D Puzzle',
    category: 'puzzle',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#10b981',
    description:
      'Full 3D Rubik’s cube simulator powered by Three.js. Orbit the camera, twist any layer clockwise or counter-clockwise, run auto-scrambles, track your solve time and move count.',
    features: [
      'Interactive 3D orbit controls and smooth layer animations',
      'Notation-based slice controls (U, D, L, R, F, B)',
      'Algorithmic random scrambler with move count target',
      'Live solve timer and move counter',
      'Auto-solve detection and victory celebration',
    ],
  },
  {
    id: 'tetris-classic',
    title: 'Tetris Classic',
    tagline: 'The tile-matching puzzle game — clear lines, chase high scores',
    genre: 'Puzzle / Arcade',
    category: 'arcade',
    status: 'playable',
    releaseYear: '1984',
    accentColor: '#a78bfa',
    description:
      'Rotate and drop tetrominoes to complete horizontal lines. Speed increases with each level. Game over when the stack reaches the top.',
    features: [
      'Seven standard tetrominoes (I, O, T, S, Z, J, L)',
      'Wall kicks and floor kicks for tight placements',
      'Next-piece preview and hold queue',
      'Accelerating gravity per level',
      'Line clear scoring: Single, Double, Triple, Tetris',
      'Ghost piece projection',
    ],
  },
  {
    id: 'sky-raid',
    title: 'Sky Raid',
    tagline: 'River raid jet shooter — shoot enemy aircraft, manage fuel, dodge terrain',
    genre: 'Arcade Shooter',
    category: 'arcade',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#0ea5e9',
    description:
      'Fly your combat jet through narrow river canyons! Shoot enemy fighter planes, helicopters, and observation balloons while flying over fuel depots to keep your tank filled.',
    features: [
      'Procedural canyon terrain scrolling at adjustable throttle',
      'Enemy variety: interceptor planes, gunship copters, balloons',
      'Fuel management mechanic with refuel depot flyovers',
      'Laser cannon ballistics and screen particle explosions',
    ],
  },
  {
    id: 'space-blast',
    title: 'Space Blast',
    tagline: 'Retro arcade space shooter across 10 progressive alien waves with mother-ship boss',
    genre: 'Space Arcade',
    category: 'arcade',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#8b5cf6',
    description:
      'Defend your sector against waves of incoming alien formations! Collect power-up shields and multi-shot upgrades, dodge enemy plasma fire, and destroy the mothership.',
    features: [
      '10 progressive difficulty waves culminating in a boss battle',
      'Power-up drops: Triple Shot, Shield Overcharge, Speed Boost',
      'Dive-bombing enemy formations with evasive maneuvers',
      'Starfield parallax backdrop with score multipliers',
    ],
  },
  {
    id: 'moto-rush',
    title: 'Moto Rush',
    tagline: 'High-speed highway motorcycle traffic dodger with near-miss bonuses',
    genre: 'Arcade Racing',
    category: 'racing',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#f97316',
    description:
      'Weave your superbike through dense highway traffic! Thread the needle between trucks and sedans for near-miss score bonuses, grab gold coins, and maintain top speed.',
    features: [
      'Multi-lane highway simulation with dynamic civilian AI traffic',
      'Near-miss bonus score multiplier for risky overtakes',
      'Nitro boost speed burst and coin magnet pickups',
      'Dynamic day-to-night lighting transitions',
    ],
  },
  {
    id: 'crazy-wheels',
    title: 'Crazy Wheels',
    tagline: 'Physics-based ragdoll obstacle trial course with lethal hazards',
    genre: 'Physics Platformer',
    category: 'action',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#e11d48',
    description:
      'Guide your bicycle rider through treacherous hazard courses filled with giant wrecking balls, spike pits, spring catapults, and explosive landmines.',
    features: [
      'Ragdoll physics simulation with momentum and rotational torque',
      'Multiple challenging obstacle stages with checkpoints',
      'Interactive hazard mechanics: spinning blades, launch pads, spikes',
      'Lean balance controls (Tilt Forward / Backward, Hop)',
    ],
  },
  {
    id: 'mini-golf',
    title: 'Mini Golf',
    tagline: '9-hole physics miniature golf course with sand traps, water hazards, and ramps',
    genre: 'Physics Sports',
    category: 'sports',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#16a34a',
    description:
      'Line up your putt, adjust power, and sink the ball in the fewest strokes! Navigate banked walls, sand bunkers, water hazards, and windmill obstacles across 9 unique holes.',
    features: [
      'Realistic ball physics with friction, slope deflection, and rebound',
      '9 hole course layout ranging from par-2 shortcuts to par-5 gauntlets',
      'Aim guide trajectory and power meter indicator',
      'Scorecard tracking under/over par status',
    ],
  },
  {
    id: 'bumper-brawl',
    title: 'Bumper Brawl',
    tagline: 'Demolition derby arena — ram rival bumper cars out of the shrinking ring',
    genre: 'Arena Combat',
    category: 'action',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#f59e0b',
    description:
      'Enter the neon bumper arena! Ram opponents to build knockback momentum, collect speed boosts, and survive as the outer edge of the arena breaks away.',
    features: [
      'Knockback physics based on vehicle collision angle and velocity',
      'Shrinking ring boundary forcing aggressive close-quarters brawls',
      'AI opponents with flanking and ramming behaviors',
      'Arena power-up spawn crates (Heavy Armor, Super Charger)',
    ],
  },
  {
    id: 'snowboard-rush',
    title: 'Snowboard Rush',
    tagline: 'Downhill alpine snowboarding with slalom gates, ski jumps, and cliff drops',
    genre: 'Alpine Sports',
    category: 'sports',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#06b6d4',
    description:
      'Carve down steep powdery mountain slopes! Slalom between pine trees and flag poles, launch off snow ramps for trick bonuses, and avoid rocky outcrops.',
    features: [
      'Downhill speed acceleration with carving drift physics',
      'Slalom gate score chains and mid-air trick rotations',
      'Environmental obstacles: tree groves, boulders, ice patches',
      'Coin collect streaks and distance meter',
    ],
  },
  {
    id: 'balloon-frenzy',
    title: 'Balloon Frenzy',
    tagline: 'Fast-paced carnival precision dart shooter with combo chains and golden targets',
    genre: 'Carnival Arcade',
    category: 'arcade',
    status: 'playable',
    releaseYear: '2026',
    accentColor: '#ec4899',
    description:
      'Test your aim in the carnival balloon gallery! Pop rising balloon clusters before time runs out. Hit special bomb balloons for screen clears and golden balloons for massive points.',
    features: [
      'Cursor-aim dart throwing physics with wind drift',
      'Special balloon types: Explosive, Freeze Timer, Gold Multiplier',
      'Rapid combo chain multipliers for uninterrupted hits',
      'Time attack and target challenge game modes',
    ],
  },
];
